#!/usr/bin/env node
// Sync the Courses vault into Quartz's content/ directory, filtered and
// reframed for students.
//
// The vault is teacher-facing: it carries planning notes, unconfirmed dates, and
// internal scheduling rationale. This script is the gate between that and the
// published site. It never writes back to the vault.
//
// Two stages: the deterministic filter below (the privacy gate — drops pages,
// strips sections, removes stamps) runs first; then reframe.mjs rewrites each
// surviving page into student-facing voice via the Claude API, cached by
// content hash in reframe-cache.json. Requires ANTHROPIC_API_KEY (or an
// `ant auth login` profile) when pages have changed; REFRAME=off skips the
// model and publishes filter-only output with a warning.
//
// Note on the notice rule: assessments must be announced *at least* one week ahead
// (AL Student Guide p.13). It is a floor, so publishing dates early is fine — it
// gives more notice, never less. Early date visibility is never a reason to withhold.

import { readFile, writeFile, mkdir, rm, readdir } from "node:fs/promises"
import { join, relative, dirname } from "node:path"
import { parseAgenda, calendarBlock, coursePage, COURSES } from "./calendar-grid.mjs"
import { courseMapHtml } from "./course-map.mjs"
import { courseDetailEvents } from "./course-events.mjs"
import { reframeAll } from "./reframe.mjs"
import { libraryMarkdown } from "./gallery.mjs"
import { insertCitations } from "./cite.mjs"

// Env overrides exist so the pipeline can be exercised off-machine against a
// fixture vault without touching the real content/. Normal use needs neither.
const VAULT = process.env.VAULT ?? "/Users/dogan/Documents/Vaults/Courses/wiki"
const OUT = process.env.OUT ?? join(import.meta.dirname, "content")

// Artwork plates, keyed by page path. Generated by images.mjs from the shared
// Image Slides library; credits.json carries the caption for each.
const HEROES = {
  "calendar.md": "calendar",
  "classes/a-level-art-design/a-level-art-design.md": "a-level-art-design",
  "classes/media-studies/media-studies.md": "media-studies",
  "classes/art-appreciation/art-appreciation.md": "art-appreciation",
  "classes/pre-a-level-art-design/pre-a-level-art-design.md": "pre-a-level-art-design",
  "classes/oxbridge/oxbridge.md": "oxbridge",
  "concepts/representation.md": "representation",
  "classes/art-appreciation/unit-plans/art-appreciation-s1-unit-3-food-the-table-and-ethics.md":
    "the-table",
  "classes/a-level-art-design/unit-plans/9479-s1-unit-2-recording-and-sustained-study.md":
    "observation",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-01-introduction-the-sketchbook-and-first-marks.md":
    "first-marks",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-02-tone-and-form.md": "tone-and-form",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-03-texture-mark-making-and-negative-space.md":
    "mark-making",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-04-composing-the-final-drawing.md":
    "composition",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-05-a1-the-final-observational-drawing.md":
    "drawn-from-life",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-06-framing-and-viewpoint.md":
    "the-great-wave",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-07-light-shadow-and-the-series-theme.md":
    "lincoln-cathedral",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-08-the-theme-shoot-and-the-contact-sheet-edit.md":
    "articles-of-glass",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-09-a2-the-photographic-series.md":
    "atget-rue-moliere",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-10-juxtaposition-and-scale.md":
    "guitar-gas-jet",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-11-layering-text-and-image.md":
    "lissitzky-schwitters",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-12-theme-and-composition-drafts.md":
    "vanitas",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-13-final-collage-production.md":
    "assembling",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-14-a3-the-final-collage.md":
    "cahun-self-portrait",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-15-the-poster-message-audience-hierarchy.md":
    "mucha-poster",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-16-a4-the-final-poster.md":
    "pioneer-girl",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-17-the-portfolio-and-the-sketchbook.md":
    "album-leaf",
  "classes/media-studies/lesson-plans/9607-s1-lesson-01-the-four-key-concepts.md":
    "seventh-regiment",
  "classes/media-studies/lesson-plans/9607-s1-lesson-02-semiotics-how-images-mean.md":
    "skull-cigarette",
  "classes/media-studies/lesson-plans/9607-s1-lesson-03-sign-types-and-codes.md":
    "calling-of-matthew",
  "classes/media-studies/lesson-plans/9607-s1-lesson-04-genre-and-camera.md": "at-the-telephone",
  "classes/media-studies/lesson-plans/9607-s1-lesson-05-narrative-and-the-planning-lock.md":
    "banqueting-sketch",
  "classes/media-studies/lesson-plans/9607-s1-lesson-06-a1-timed-media-language-analysis.md":
    "whittier-classroom",
  "classes/media-studies/lesson-plans/9607-s1-lesson-07-reading-systematically-toward-the-blog-midpoint.md":
    "wanderer",
  "classes/media-studies/lesson-plans/9607-s1-lesson-08-representation-applied-to-your-own-product.md":
    "kasebier-wild-west",
  "classes/media-studies/lesson-plans/9607-s1-lesson-09-the-gaze.md": "folies-bergere",
  "classes/media-studies/lesson-plans/9607-s1-lesson-10-the-creative-critical-reflection.md":
    "rivera-self-portrait",
  "classes/media-studies/lesson-plans/9607-s1-lesson-11-audiences-and-the-portfolio-submission.md":
    "good-glass-of-beer",
  "classes/media-studies/lesson-plans/9607-s1-lesson-12-institutions-and-section-a-craft.md":
    "above-fifth-avenue",
  "classes/media-studies/lesson-plans/9607-s1-lesson-13-a4-section-a-in-authentic-format.md":
    "lindbergh-1927",
  "classes/media-studies/lesson-plans/9607-s1-lesson-14-consolidation-and-the-coverage-matrix.md":
    "moon-atlas",
  "classes/media-studies/lesson-plans/9607-s1-lesson-15-exam-rehearsal.md": "musicians",
  "classes/media-studies/lesson-plans/9607-s1-lesson-16-end-of-term-exam-and-return.md":
    "the-magpie",
}

// In-copyright works cited in lessons — named and linked, never embedded (see
// cite.mjs). Same shape as FIGURES (keyed by vault path, injected after the
// paragraph matching `anchor`), but renders a citation line, not an image. Add
// `src` for a "view →" link; omit it for a placeholder. Public-domain works go
// through FIGURES/HEROES as actual images instead.
const CITATIONS = {
  "classes/media-studies/lesson-plans/9607-s1-lesson-09-the-gaze.md": [
    { cite: "Cindy Sherman, *Untitled Film Still #21*, 1978", anchor: /three looks/i },
  ],
}

// Inline figures (2026-07-21): lesson pages carry period exemplars from the shared
// library, inserted after the paragraph that first matches `anchor`. Anchors are
// content facts rather than headings, chosen to survive the reframe stage; an
// unmatched figure lands at the end of the body instead of vanishing, so the git
// diff of content/ shows exactly where each one settled. Entries with several
// slugs render side by side as a .plate-row grid.
const FIGURES = {
  // ── Art Appreciation S1 (period exemplars, one per lesson) ────────────────
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-01-opening-the-atlas.md": [
    { slugs: ["articles-of-glass"], anchor: /physical trace|light did to a surface/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-02-what-survives-and-why.md": [
    { slugs: ["mummy-portrait"], anchor: /the wall is the evidence|what had to happen for an object to reach you/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-03-the-first-board.md": [
    { slugs: ["deer-mandala"], anchor: /ritual objects and ancestral presence/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-04-telling-it-without-words.md": [
    { slugs: ["calling-of-matthew"], anchor: /where a still image puts time/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-05-titian-to-manet.md": [
    { slugs: ["folies-bergere"], anchor: /refusals Manet is making|Manet, \*Olympia\*/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-06-the-table-as-moral-space.md": [
    { slugs: ["the-table"], anchor: /three paintings of meals|who is where/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-07-the-split-weeks.md": [
    { slugs: ["composition"], anchor: /your own table/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-08-heda-and-the-image-of-work.md": [
    { slugs: ["heda-still-life"], anchor: /the still life as inventory/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-09-food-the-table-and-ethics.md": [
    { slugs: ["last-supper"], anchor: /one claim about food and ethics|food and ethics, argued from the pictures/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-10-berger-and-the-reproduction.md": [
    { slugs: ["the-magpie"], anchor: /a reproduction is not a neutral copy/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-11-aura-and-the-poor-image.md": [
    { slugs: ["representation"], anchor: /a print is many/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-12-photography-and-after.md": [
    { slugs: ["the-great-wave"], anchor: /why we believe photographs|photography and the claim to truth/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-13-the-artworld-and-the-brief.md": [
    { slugs: ["guitar-gas-jet"], anchor: /the artworld and the end of art|what makes something art when looking cannot tell you/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-14-the-retrospective.md": [
    { slugs: ["album-leaf"], anchor: /read back as one argument/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-15-return.md": [
    { slugs: ["wanderer"], anchor: /Semester 2 trailer|re-read their own work/i },
  ],
  // ── A Level Art & Design S1 (C1 Portfolio) — one artwork per pipeline stage ──
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-01-introduction-and-the-theme-menu.md": [
    { slugs: ["a-level-art-design"], anchor: /top-band portfolio|committed to one theme|theme menu/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-02-formal-elements-on-the-theme.md": [
    { slugs: ["mark-making"], anchor: /five different instruments|each formal element/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-03-intention-and-composition-planning.md": [
    { slugs: ["banqueting-sketch"], anchor: /the theme becomes an investigation|composition planning/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-04-the-sustained-study.md": [
    { slugs: ["observation"], anchor: /One long observed study|the spine of AO1|Stage 1 page/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-05-recording-pages-and-a1.md": [
    { slugs: ["drawn-from-life"], anchor: /pages an examiner could read/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-06-media-exploration.md": [
    { slugs: ["repin-nevsky-studies"], anchor: /twelve prescribed experiments|which media carry the theme/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-07-selection-and-scale.md": [
    { slugs: ["tone-and-form"], anchor: /select your media|the exploration becomes a commitment/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-08-artist-study-1.md": [
    { slugs: ["van-gogh-armchair"], anchor: /they solve the problem in your work|first artist/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-09-artist-2-bridge-piece-and-a2.md": [
    { slugs: ["repin-cossacks-study"], anchor: /second artist against the first|from study into develop/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-10-composition-1.md": [
    { slugs: ["composition"], anchor: /from your own recorded studies|never from memory/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-11-composition-2-and-critique.md": [
    { slugs: ["vanitas"], anchor: /the alternative you did not take|built with the same effort/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-12-targeted-tests-and-direction.md": [
    { slugs: ["skull-cigarette"], anchor: /what the critique left unresolved|targeted tests/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-13-final-plan-and-a3.md": [
    { slugs: ["van-gogh-outskirts"], anchor: /solved small|palette and materials are settled/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-14-the-final-outcome.md": [
    { slugs: ["cafe-terrace"], anchor: /one continuous run|underdrawing through to surface/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-15-submission-week-and-a4.md": [
    { slugs: ["the-great-wave"], anchor: /the photograph is the version the examiner sees/i },
  ],
  // ── A Level Art & Design S2 (C3 Personal Investigation) — same stage signatures ──
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-01-opening-the-investigation.md": [
    { slugs: ["first-marks"], anchor: /read a 90\/100 investigation|propose the theme yourself|most consequential/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-02-proposal-and-feasibility.md": [
    { slugs: ["banqueting-sketch"], anchor: /stress-test the whole thing|a proposal you can defend/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-03-theme-locked.md": [
    { slugs: ["a-level-art-design"], anchor: /lock it in writing|no restarts/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-04-recording-and-the-a1-milestone.md": [
    { slugs: ["drawn-from-life"], anchor: /makes your thinking visible to a stranger|one sustained study/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-05-recording-pages-and-feedback.md": [
    { slugs: ["repin-nevsky-studies"], anchor: /three specific actions|build the recording pages/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-06-media-exploration.md": [
    { slugs: ["mark-making"], anchor: /twelve media experiments|experiments built so they/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-07-artist-1-in-full.md": [
    { slugs: ["van-gogh-armchair"], anchor: /an artist who solves the problem|copy to understand/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-08-artist-2-bridge-and-a2.md": [
    { slugs: ["repin-cossacks-study"], anchor: /a different angle on the same problem|the bridge piece/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-09-composition-1.md": [
    { slugs: ["composition"], anchor: /from your own studies|hold one idea across two/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-10-resolving-composition-1.md": [
    { slugs: ["tone-and-form"], anchor: /Unresolved work cannot be judged|resolve composition 1/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-11-composition-2-and-paper-drafts.md": [
    { slugs: ["vanitas"], anchor: /the rejected alternative|equal effort/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-12-critique-and-targeted-tests.md": [
    { slugs: ["skull-cigarette"], anchor: /only what is unresolved|choosing is development/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-13-evaluation-draft-1-and-a3.md": [
    { slugs: ["van-gogh-outskirts"], anchor: /against your intention, not the effort|trail of decisions/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-14-mid-point-piece-and-bibliography.md": [
    { slugs: ["observation"], anchor: /choose the piece that carries the investigation|into the body of the work/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-15-submission-week-and-a4.md": [
    { slugs: ["the-great-wave"], anchor: /the photograph is the version the examiner sees/i },
  ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-06-framing-and-viewpoint.md": [
    {
      slugs: ["sea-of-steps", "st-pauls-spires", "canon-de-chelle"],
      anchor: /vantage point|rule of thirds/i,
    },
  ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-07-light-shadow-and-the-series-theme.md":
    [
      {
        slugs: ["girl-with-washington", "kasebier-portrait", "the-tugboat"],
        anchor: /diffused/i,
      },
      { slugs: ["cloud-sequence"], anchor: /Ueda|one subject, idea, or rule/i },
    ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-08-the-theme-shoot-and-the-contact-sheet-edit.md":
    [
      {
        slugs: ["yosemite-mosquito-camp", "yosemite-rocky-ford"],
        anchor: /everything small|contact sheet:/i,
      },
    ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-09-a2-the-photographic-series.md": [
    {
      slugs: ["atget-rue-mazet", "atget-avenue-de-suffren", "atget-rue-mazarine"],
      anchor: /take any one image away|kill-your-darlings/i,
    },
    { slugs: ["yosemite-fall"], anchor: /opener/i },
  ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-10-juxtaposition-and-scale.md": [
    { slugs: ["kahnweiler"], anchor: /glue newspaper|papier collé/i },
  ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-11-layering-text-and-image.md": [
    {
      slugs: ["talbot-lace", "rubens-title-page"],
      anchor: /torn edge|transparency/i,
    },
  ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-12-theme-and-composition-drafts.md": [
    { slugs: ["impossible-bouquet"], anchor: /vanitas|none of this lasts/i },
  ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-15-the-poster-message-audience-hierarchy.md":
    [
      {
        slugs: ["gsell-advertisement", "kawase-temple"],
        anchor: /name card|Ukiyo-e|first read/i,
      },
    ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-01-the-four-key-concepts.md": [
    {
      // Target the D2 mediation-demo list, not the Goal paragraph (which also
      // says "a version, not a window"). "Anchorage" is the list's last bullet,
      // so the pair lands after the three mechanisms.
      slugs: ["rebel-sharpshooter", "migrant-mother"],
      anchor: /- \*\*Anchorage\*\*/,
    },
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-02-semiotics-how-images-mean.md": [
    { slugs: ["mummy-portrait"], anchor: /connotation chains|who taught you that/i },
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-03-sign-types-and-codes.md": [
    {
      slugs: ["nadar-taylor", "talbot-lace-index", "deer-mandala"],
      anchor: /an index that looks like an icon|means by convention/i,
    },
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-04-genre-and-camera.md": [
    {
      slugs: ["vanitas-schaak", "vanitas-schoor"],
      anchor: /that recognition is genre|belong together/i,
    },
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-05-narrative-and-the-planning-lock.md": [
    { slugs: ["peasant-wedding"], anchor: /by what they do, not who they are|donor/i },
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-06-a1-timed-media-language-analysis.md": [
    {
      slugs: ["vivarini-exorcism"],
      anchor: /where did Propp fail|withheld function/i,
    },
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-07-reading-systematically-toward-the-blog-midpoint.md":
    [
      {
        slugs: ["hampton-geography"],
        anchor: /describe → question → suggest|audited post by post/i,
      },
    ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-08-representation-applied-to-your-own-product.md":
    [{ slugs: ["lincoln-mcclellan"], anchor: /photo-op is older than the word|posed in a tent/i }],
  "classes/media-studies/lesson-plans/9607-s1-lesson-09-the-gaze.md": [
    { slugs: ["cahun-gaze"], anchor: /oppositional gaze|looking back at a text/i },
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-12-institutions-and-section-a-craft.md": [
    {
      slugs: ["emperors-table"],
      anchor: /frame belonged to the payer|imperial commission|Emperor's camp/i,
    },
  ],
}

const credits = JSON.parse(await readFile(join(import.meta.dirname, "credits.json"), "utf8"))

// Depth-relative path, so the site still works if it's ever served from a subpath.
function figureHtml(slug, depth, cls = "plate") {
  const credit = credits[slug]
  if (!credit) return ""
  const prefix = "../".repeat(depth)
  const caption = credit.replace(/\*([^*]+)\*/g, "<em>$1</em>")
  const alt = credit.replace(/\*/g, "")
  return (
    `<figure class="${cls}">\n` +
    `  <img src="${prefix}static/img/${slug}.jpg" alt="${alt}" loading="lazy" />\n` +
    `  <figcaption>${caption}</figcaption>\n` +
    `</figure>\n`
  )
}

const heroFigure = (slug, depth) => {
  const html = figureHtml(slug, depth, "plate plate--hero")
  return html && html + "\n"
}

// A FIGURES entry rendered to HTML: one figure, or several in a .plate-row grid.
function figureBlock(slugs, depth) {
  const figs = slugs.map((s) => figureHtml(s, depth)).filter(Boolean)
  if (!figs.length) return ""
  if (figs.length === 1) return figs[0] + "\n"
  return `<div class="plate-row">\n${figs.join("")}</div>\n\n`
}

// Insert each figure after its anchor's first match: directly after the matched
// bullet when the anchor lands inside a list item (splitting the list around the
// figure), otherwise after the containing paragraph; no match → end of the body.
function insertFigures(body, entries, depth) {
  for (const entry of entries) {
    const html = figureBlock(entry.slugs, depth)
    if (!html) continue
    const at = body.search(entry.anchor)
    if (at === -1) {
      body = body.trimEnd() + "\n\n" + html
      continue
    }
    const lineStart = body.lastIndexOf("\n", at) + 1
    const lineEnd = body.indexOf("\n", at)
    const line = body.slice(lineStart, lineEnd === -1 ? body.length : lineEnd)
    const isBullet = /^\s*- /.test(line)
    let pos
    if (isBullet && lineEnd !== -1) pos = lineEnd + 1
    else {
      const paraEnd = body.indexOf("\n\n", at)
      pos = paraEnd === -1 ? -1 : paraEnd + 2
    }
    body =
      pos === -1
        ? body.trimEnd() + "\n\n" + html
        : body.slice(0, pos) + "\n" + html + body.slice(pos)
  }
  return body
}

// Pages that never reach students. Paths are relative to the vault's wiki/ root.
const DROP_PAGES = new Set([
  "index.md", // routing table for the LLM, not readers
  "log.md", // append-only operation history
  "courses-dashboard.md", // congestion analysis, risks, open questions
  "shared/first-session-opener.md", // teaching script for the opener
  "shared/image-slide-library.md", // internal 6,181-image asset catalog
  // Every student-relevant date on it already appears on the hub calendar page (a
  // strict superset — verified 2026-07-20); what remains is planning analysis:
  // source-file provenance, correction history, cohort caveats, upstream defects.
  "shared/school-academic-calendar.md",
  "classes/pre-a-level-art-design/lesson-plans/pal-legacy-lesson-library.md", // marked SUPERSEDED
  "classes/pre-a-level-art-design/pal-prior-plans.md", // prior-plans catalog: teacher planning reference (added 2026-07-20)
  "classes/art-appreciation/lesson-plans/art-appreciation-legacy-lesson-bank.md", // prior generation
  "classes/art-appreciation/unit-plans/art-appreciation-food-and-ethics-prior-unit.md", // prior generation
  // Provenance analysis, teacher-facing in its entirety: which theorists are
  // Cambridge's vs the centre's, what the vault holds no readings for (2026-07-20).
  "analyses/9607-theory-provenance.md",
  // The vault's home page is a teacher's dashboard: vault status, the live Bases
  // table, links to the index and dashboard. The site gets site-home.md instead.
  "home.md",
])

// Assessment registers ARE published — students get real value from the per-item
// dates, formats and AO focus. Their internal parts (the "Announced"/"Gap" columns,
// the notice-correction and timetable-redraw callouts, and the trailing rules/
// open-items sections) are stripped by cleanRegister() below. Nothing is withheld
// wholesale by directory anymore.
const DROP_DIRS = []

// H2 sections removed from every page that has them.
const STRIP_SECTIONS = [
  "Teacher notes",
  "Contingencies",
  "Contingencies & open items",
  "Open items",
  "Open items, explained",
  // Assessment-register rule sections: internal scheduling logic, and the general
  // grading rules they restate are already on the published framework page.
  "Applied rules",
  "Notice and marking rules", // "…, as applied"
  "The 13 applied handbook rules", // PAL; heading actually reads "(compact)"
  "Gaps",
  "Image and library needs",
  "Class workspace", // raw/ paths and ingest instructions
  "Holdings", // inventory of source files in raw/
  // Resource-library catalog sections: teacher inventory of raw/ teaching files,
  // with slide counts, an "I cannot watch video" note, and worksheet-as-assessment
  // warnings. The reading sections are kept and cleaned by cleanResourceLibrary().
  "Slide decks",
  "Videos",
  "Worksheets",
  // Course-overview sections that are planning notes about the vault itself:
  // which sources disagree, what is still undecided, what is missing.
  "⚠ Old-spec traps",
  "⚠ The syllabus straddle",
  "Open decisions",
  "Known inconsistencies",
  "Missing from",
  "Flags",
  "Two generations of the course",
  "Teaching materials",
  "Heavy dependence on the shared library",
  "Shared-library touchpoints",
  "Information needed",
  // Unit-page sections added 2026-07-20: teacher mappings of raw/ files to sessions,
  // and prior-year plan mining notes. Both reference raw/ paths and usage guidance.
  "Resources",
  "Prior plan",
  "Course-wide references", // resource-library catalog section (AO guide, elements chart)
]

// Matched as a prefix, so "## Gaps this material does *not* fill" is caught by "Gaps".
// Safe for this list: none of these names begins a student-facing heading.

const isDropped = (rel) => DROP_PAGES.has(rel) || DROP_DIRS.some((d) => rel.includes(d))

async function walk(dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...(await walk(full)))
    else if (entry.name.endsWith(".md")) out.push(full)
  }
  return out
}

// Remove an H2 section: the heading through to the next H2 or end of file.
function stripSections(body) {
  for (const name of STRIP_SECTIONS) {
    const esc = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    // Terminate at the next H2 or end of file. JS has no \z, so the alternative
    // is a negative lookahead for any remaining character.
    body = body.replace(new RegExp(`^## ${esc}.*$[\\s\\S]*?(?=^## |(?![\\s\\S]))`, "gm"), "")
  }
  return body
}

// Split a markdown table row into cells, respecting `\|` escapes — the registers
// carry `[[path\|alias]]` wikilinks whose pipe must not be read as a column break.
function splitRow(line) {
  const cells = line.split(/(?<!\\)\|/)
  if (cells.length && cells[0].trim() === "") cells.shift()
  if (cells.length && cells[cells.length - 1].trim() === "") cells.pop()
  return cells
}

// Remove named columns from every GitHub-style table in the text. Used to drop the
// internal "Announced" and "Gap" columns while keeping the student-facing ones.
function dropTableColumns(body, dropHeaders) {
  const lines = body.split("\n")
  const out = []
  for (let i = 0; i < lines.length; i++) {
    const sep = lines[i + 1]
    const isTableHead =
      lines[i].includes("|") && sep && /-/.test(sep) && /^\s*\|?[\s:|-]+\|[\s:|-]*$/.test(sep)
    if (!isTableHead) {
      out.push(lines[i])
      continue
    }
    const drop = new Set(
      splitRow(lines[i])
        .map((h, idx) => (dropHeaders.includes(h.trim()) ? idx : -1))
        .filter((idx) => idx >= 0),
    )
    if (drop.size === 0) {
      out.push(lines[i])
      continue
    }
    let j = i
    while (j < lines.length && lines[j].includes("|") && lines[j].trim() !== "") {
      const kept = splitRow(lines[j]).filter((_, idx) => !drop.has(idx))
      out.push("| " + kept.map((c) => c.trim()).join(" | ") + " |")
      j++
    }
    i = j - 1
  }
  return out.join("\n")
}

// The whole-paragraph and sentence-level internal bits that survive the section and
// column strips — announcement scheduling, timetable contingencies, planning stamps.
// Matched by distinctive substrings so the surrounding student-facing prose stays.
const INTERNAL_PARAGRAPHS = [
  "exposed to Foreign Culture Day", // 9479 CS Friday-slip note
  "each derived against", // Art App Majors intro (announcement scheduling)
  "announcements land 14 days ahead", // PAL attainment note
  "CS notice per handbook", // PAL CS note
  "the two remaining courses with the same gap", // 9479 Final cross-course contrast
  // PAL sketchbook (2026-07-20): A5 (2027-01-06) and the two spot-checks SB1/SB2 are
  // all dated now and publish via the register tables + clean notes. Still teacher-only:
  "Format spec exists", // EoT pointer into prior-plans (teacher material)
]

// Register-only cleanup, on top of the shared section strip.
function cleanRegister(body) {
  // Every blockquote in these registers is internal: the notice-rule correction,
  // the "timetable has no Thursday" redraw, and the `> **Codes:**` mapping note.
  body = body.replace(/(?:^>.*(?:\n|$))+/gm, "")

  body = dropTableColumns(body, ["Announced", "Gap"])

  body = body
    .split(/\n\n+/)
    .filter((para) => !INTERNAL_PARAGRAPHS.some((s) => para.includes(s)))
    .join("\n\n")

  // Register-only planning tails. (The "Confirmed by the human" stamp is handled
  // globally by stripStamp, since it appears on many non-register pages too.)
  // These run from their marker to the end of the paragraph and stop at the break,
  // so the following heading survives.
  body = body
    .replace(/[ \t]*\*\*Resolved [^*]*?\.\*\*[ \t]*/g, "")
    .replace(/[ \t]*Open question:[\s\S]*?(?=\n\n|$)/g, "")
    .replace(/[ \t]+\n/g, "\n")

  return body
}

// The vault stamps human-confirmed facts as "Confirmed by the human <date>" (and a
// lowercase "(confirmed <date>)" variant) — an authoring convention, never for
// students. Drop the stamp, keep the fact. Applied to every page. Same treatment
// for ingest stamps ("(ingested 2026-07-20)", "Ingested 2026-07-19.") — they date
// when a source entered the vault, which means nothing to a reader.
function stripStamp(body) {
  return (
    body
      // Prefix form "Confirmed by the human <date>: Fact" / "…<date>, Fact" → "Fact".
      .replace(
        /Confirmed by the human 20\d\d-\d\d-\d\d[:,]\s*(\*{0,2})([a-z])/g,
        (_, emph, ch) => emph + ch.toUpperCase(),
      )
      // Standalone / trailing stamp, with any leading comma, semicolon or space.
      .replace(/[,;]?\s*Confirmed by the human 20\d\d-\d\d-\d\d/g, "")
      // Parenthetical "(confirmed with the human <date>)" variant.
      .replace(/\s*\((?:re-?)?confirmed with the human[^)]*\)/gi, "")
      // Lowercase parenthetical "(confirmed <date>[, …])", incl. "(re-confirmed 07-20)".
      .replace(/\s*\((?:re-?)?confirmed (?:20\d\d-)?\d\d-\d\d[^)]*\)/gi, "")
      // Ingest stamps: "(ingested 2026-07-20)" — inline and in headings — and the
      // standalone sentence "Ingested 2026-07-19."
      .replace(/\s*\((?:re-)?ingested (?:20\d\d-)?\d\d-\d\d[^)]*\)/gi, "")
      .replace(/\s*Ingested 20\d\d-\d\d-\d\d\./g, "")
      // Empty bold left when the stamp was the whole bold span: "**** — a studio…" →
      // "A studio…"; bare "****" → "".
      .replace(/\*\*\s*\*\*\s*—\s*([a-z])/g, (_, ch) => ch.toUpperCase())
      .replace(/\*\*\s*\*\*/g, "")
      .replace(/[ \t]{2,}/g, " ")
      .replace(/[ \t]+([.,;])/g, "$1")
  )
}

// Students see assessments at their real dates (the calendar and the register tables).
// The vault also models when each is *announced* — teacher scheduling that means nothing
// to a student. Strip the announcement notes, keeping the assignment itself. Not applied
// to the framework page, which legitimately explains the one-week notice policy.
function stripAnnouncements(body) {
  return (
    body
      // Parenthetical note that mixes announcement with a return date:
      // "(announced 11-13; returned Tue 12-01)" → "(returned Tue 12-01)".
      .replace(/\(announced [^;)]*;\s*/gi, "(")
      // Announcement-only parenthetical: "(announced 09-30)" / "(announced Tue 12-01)" → "".
      .replace(/\s*\(announced[^)]*\)/gi, "")
      // Clause after a sit date: "sits <date>, announced <date> — see …" → drop the clause.
      // The lookahead leaves the boundary punctuation and any space before it intact, so
      // "sits <date>, announced <date> — see" becomes "sits <date> — see", not "…date— see".
      .replace(/\s*[—,]\s*announced\b[^.;,—|)]*?(?=\s*[.;,—|)]|$)/gi, "")
      // Prose clause "…; announced <date> (reason)…" → drop to the next . ; or cell edge.
      .replace(/;\s*announced\b[^.;|]*?(?=\s*[.;|]|$)/gi, "")
      // Whole bold sentence about announcement: "**A4 is announced on the A3 sitting day**".
      .replace(/\*\*A\d is announced[^*]*\*\*/gi, "")
      // Session-table / inline markers, with an optional leading "·" or ";" separator:
      // "A2 announced", "A1 + CS1 announced", "**A3 announced**", "**CS4** · A4 announced".
      .replace(/(?:\s*[·;]\s*)?\*{0,2}A\d(?:\s*\+\s*CS\d)?\s+announced\*{0,2}/g, "")
      // Register cell note "— announced with A1 on 09-16" and "A4's announcement on 12-16".
      .replace(/\s*—?\s*announced with [^|.\n]*/gi, "")
      .replace(/\s*A\d's announcement on \d\d-\d\d/gi, "")
      // "announced here at U1·L10" / "**announced here**" and bare "announced here".
      .replace(/\*{0,2}announced here\*{0,2}(?:\s+at\s+[^.;|]*)?/gi, "")
      // Register-pointer phrasing on semester/unit pages: keep the pointer, drop the
      // "announcement dates and rules" / "the announcement rule (…)" descriptor.
      .replace(/\s*with (?:the full )?announcement dates and rules/gi, "")
      .replace(/\s*with the announcement rule \([^)]*\)/gi, "")
      // Tidy: empty parens, cell-initial dangling separators, doubled spaces.
      .replace(/\(\s*\)/g, "")
      .replace(/(\|\s*)[;·]\s+/g, "$1")
      .replace(/[ \t]{2,}/g, " ")
      .replace(/[ \t]+([.,;])/g, "$1")
      .replace(/[ \t]+\|/g, " |")
      .replace(/[ \t]+\n/g, "\n")
  )
}

// The resource-library page is a teacher catalog of raw/ files. With its inventory
// sections stripped (Slide decks / Videos / Worksheets / Gaps), what remains is the
// two reading tables — this reframes them as a student reading list: the "teacher
// reference" shelf becomes "Further reading", and the catalog/ingest framing goes.
function cleanResourceLibrary(body) {
  return (
    body
      .replace(/^## Readings — teacher reference\s*$/m, "## Further reading")
      // Framing lines written for the teacher, not the reader.
      .replace(/^Not student-facing\. [^\n]*\n/m, "")
      .replace(/^Confirmed with the human 20\d\d-\d\d-\d\d as student-facing\.\s*\n/m, "")
      .replace(/^Catalog of `raw\/[^\n]*\n/m, "")
      .replace(/^\*\*Catalogued, not transcribed\.\*\* [^\n]*\n/m, "")
      .replace(/^The important thing this drop changes:[^\n]*\n/m, "")
      // Closing line of vault analysis ("assembled for the current arc, not the prior unit").
      .replace(/^Six of the seven map onto lessons[^\n]*\n/m, "")
      .replace(/\n{3,}/g, "\n\n")
  )
}

// The calendar page carries Obsidian-only framing: a pointer to the Full Calendar
// plugin (which doesn't exist on the web) and a vault-maintenance "derived view"
// note. Strip both so the agenda reads as the calendar, not a mirror of one.
function cleanCalendar(body) {
  return (
    body
      .replace(/\s*For the visual month\/week view[\s\S]*?greppable list\./, "")
      .replace(/^This is a \*derived view\*[\s\S]*?needs fixing\.\s*$/m, "")
      // The "⚠️ Confirm before term" section is a teacher's pre-term checklist
      // (TBC items, resolution history). Drop the section but keep its closing
      // italic note — that paragraph tells students where CS/HW schedules live.
      .replace(/^## ⚠️? ?Confirm before term[\s\S]*?(?=^\*This calendar lists|(?![\s\S]))/m, "")
      .replace(/\n{3,}/g, "\n\n")
  )
}

// Withheld pages whose student-relevant content lives on another published page:
// links to them are retargeted there instead of degrading to plain text.
const LINK_REDIRECTS = {
  // The hub calendar is a strict superset of the school calendar's dates.
  "shared/school-academic-calendar": "calendar",
}

// Links to withheld pages are retargeted (if a redirect exists) or become plain
// text, so the site has no dead ends. Handles [[path]], [[path|alias]] and the
// [[path\|alias]] form used inside tables.
function derefDropped(text, publishedTargets) {
  return text.replace(/\[\[([^\]|]+?)(?:(\\?\|)([^\]]*?))?\]\]/g, (match, target, pipe, alias) => {
    const clean = target.split("#")[0].trim()
    if (publishedTargets.has(clean)) return match
    // Humanize the slug for bare links, so prose reads "the school academic
    // calendar", not "the school-academic-calendar".
    const label = alias ?? clean.split("/").pop().replace(/-/g, " ")
    const redirect = LINK_REDIRECTS[clean]
    if (redirect) return `[[${redirect}${pipe ?? "|"}${label}]]`
    return label
  })
}

// Drop `sources:` (raw/ paths are internal), `tags:` (vault taxonomy — the site
// has no tag pages), and prune `related:` of withheld pages.
function cleanFrontmatter(fm, publishedTargets) {
  const lines = fm.split("\n")
  const kept = []
  let inSources = false
  for (const line of lines) {
    if (/^tags:/.test(line)) continue
    if (/^sources:/.test(line)) {
      inSources = true
      continue
    }
    if (inSources) {
      if (/^\s+-\s/.test(line)) continue
      inSources = false
    }
    // Prune related: entries whose target is withheld.
    const relatedEntry = line.match(/^\s+-\s+"\[\[([^\]|]+?)(?:\|[^\]]*)?\]\]"\s*$/)
    if (relatedEntry && !publishedTargets.has(relatedEntry[1].split("#")[0].trim())) continue
    // content/ is regenerated on every sync, so filesystem mtimes are meaningless.
    // The vault's own last_updated is the honest date; Quartz reads `modified`.
    kept.push(line.replace(/^last_updated:/, "modified:"))
  }
  return kept.join("\n")
}

const files = await walk(VAULT)
const published = files.map((f) => relative(VAULT, f)).filter((rel) => !isDropped(rel))

// Wikilinks in this vault use full vault-relative paths without the .md suffix.
const publishedTargets = new Set(published.map((rel) => rel.replace(/\.md$/, "")))

// ── Phase 1: deterministic filter ───────────────────────────────────────────
// This is the privacy gate. Everything below runs before any model sees a page:
// withheld pages and stripped sections never leave this machine.

// rel → frontmatter title, for the course maps and nav labels.
const pageTitles = new Map()
// lesson rel → base filename of the unit it belongs to (from its `related`
// frontmatter links), so the course map can nest lessons under their units.
const lessonUnits = new Map()
let strippedCount = 0
const pages = []
for (const rel of published) {
  let raw = await readFile(join(VAULT, rel), "utf8")

  const fmMatch = raw.match(/^---\n([\s\S]*?)\n---\n/)
  let frontmatter = ""
  let body = raw
  if (fmMatch) {
    frontmatter = cleanFrontmatter(fmMatch[1], publishedTargets)
    body = raw.slice(fmMatch[0].length)
    const t = fmMatch[1].match(/^title:\s*"?(.+?)"?\s*$/m)
    if (t) pageTitles.set(rel, t[1])
    if (rel.includes("lesson-plans/")) {
      const u = fmMatch[1].match(/unit-plans\/([^\]|/\n]+)/)
      if (u) lessonUnits.set(rel, u[1])
    }
  }

  const before = body.length
  body = stripSections(body)
  if (rel.includes("/assessments/")) body = cleanRegister(body)
  if (rel.endsWith("resource-library.md")) body = cleanResourceLibrary(body)
  if (rel === "calendar.md") body = cleanCalendar(body)
  body = stripStamp(body)
  // The framework page explains the one-week notice policy — student-useful, keep it.
  if (rel !== "shared/bnds-assessment-framework.md") body = stripAnnouncements(body)
  if (body.length !== before) strippedCount++

  // The Bases plugin embed can't render outside Obsidian.
  body = body.replace(/^!\[\[dashboard\.base\]\]\s*$/gm, "")

  body = derefDropped(body, publishedTargets)
  body = body.replace(/\n{3,}/g, "\n\n").trimEnd() + "\n"

  pages.push({ rel, frontmatter, body })
}

// ── Phase 2: student-voice reframe ──────────────────────────────────────────
// The filter above can only *delete* teacher material; the surviving prose is
// still written in the vault's planning voice. This stage rewrites each body
// for students via the Claude API (see reframe.mjs), cached by content hash so
// only changed pages cost a model call. It runs before content/ is cleared, so
// a failure aborts with the previous output intact.
const SKIP_REFRAME = new Set([
  // A dates-only agenda, already cleaned by cleanCalendar(); the month-view
  // injection below anchors on its "## … Agenda" heading, which must survive.
  "calendar.md",
])
const reframeStats = await reframeAll(
  pages.filter((p) => !SKIP_REFRAME.has(p.rel)),
  {
    cachePath: join(import.meta.dirname, "reframe-cache.json"),
    disabled: process.env.REFRAME === "off",
  },
)

// ── Student-facing titles ───────────────────────────────────────────────────
// Vault titles carry the teacher's taxonomy ("9607 S1 Lesson 02: …") — syllabus
// code and semester on every page. On the site the course is always visible
// (nav, breadcrumbs, the context strip), so titles keep only what a student
// needs: "Lesson 02: …". Course-level pages keep the course name because their
// names collide across courses in search ("Semester 1 Plan" × 5). Applied in
// phase 3, after the reframe, so the cache (keyed on the phase-1 body) is
// untouched. A Level spans four semesters with repeating unit names, so it
// keeps the S# marker.
const MULTI_SEMESTER = new Set(["classes/a-level-art-design"])

function studentTitle(rel, title) {
  const course = Object.values(COURSES).find((c) => rel.startsWith(c.dir + "/"))
  if (!course || !title) return title
  const multi = MULTI_SEMESTER.has(course.dir)
  let m = title.match(/^.*?\bS(\d)\s+Lesson (\d+):\s*(.+)$/i)
  if (m) return multi ? `S${m[1]} Lesson ${m[2]}: ${m[3]}` : `Lesson ${m[2]}: ${m[3]}`
  m = title.match(/^.*?\bS(\d)\s+U(?:nit)?\s*(\d+):\s*(.+)$/i)
  if (m) return multi ? `S${m[1]} Unit ${m[2]}: ${m[3]}` : `Unit ${m[2]}: ${m[3]}`
  m = title.match(/^.*?\bS(\d) Assessments$/i)
  if (m) return `${course.name} · S${m[1]} Assessments`
  m = title.match(/^(?:9479|9607|PAL|Art Appreciation|Pre A Level(?: Art & Design)?)\s+(.+)$/)
  if (m) return `${course.name} · ${m[1]}`
  return title
}

// Bare full-path wikilinks render as their slug ("bnds-assessment-framework");
// alias them with the target's title so prose reads like prose. Table rows are
// skipped — a raw "|" inside a cell would break the row, and links there
// already use the [[path\|alias]] form.
function aliasBareLinks(body, titles) {
  return body
    .split("\n")
    .map((line) => {
      if (line.includes("|")) return line
      return line.replace(/\[\[([^\]|#\\]+)\]\]/g, (match, target) => {
        const title = titles.get(target.trim())
        return title ? `[[${target.trim()}|${title}]]` : match
      })
    })
    .join("\n")
}

// New titles for every published page, and the alias lookup keyed by wikilink
// target. pageTitles is updated in place so the course-map injection below and
// the nav labels derived from frontmatter stay consistent.
const studentTitles = new Map()
for (const rel of published) {
  const t = studentTitle(rel, pageTitles.get(rel))
  if (!t) continue
  pageTitles.set(rel, t)
  studentTitles.set(rel.replace(/\.md$/, ""), t)
}

// ── Phase 3: write content/ ─────────────────────────────────────────────────
await rm(OUT, { recursive: true, force: true })
await mkdir(OUT, { recursive: true })

// Every path this run writes, so anything else in content/ can be pruned at the end.
const written = new Set()
for (const { rel, frontmatter: fm, body: cleaned } of pages) {
  let body = cleaned
  let frontmatter = fm

  // Student-facing title: rewrite the frontmatter `title:` and the H1 to match.
  // The reframe keeps H1s verbatim, so the original title is still on that line.
  const newTitle = pageTitles.get(rel)
  const oldTitle = fm?.match(/^title:\s*"?(.+?)"?\s*$/m)?.[1]
  if (newTitle && oldTitle && newTitle !== oldTitle) {
    frontmatter = frontmatter.replace(/^title:.*$/m, `title: "${newTitle}"`)
    body = body.replace(`# ${oldTitle}`, `# ${newTitle}`)
  }

  body = aliasBareLinks(body, studentTitles)

  const depth = rel.split("/").length - 1
  // Figures first: their anchors must match page content, not the hero's caption.
  if (FIGURES[rel]) body = insertFigures(body, FIGURES[rel], depth)
  if (CITATIONS[rel]) body = insertCitations(body, CITATIONS[rel])
  if (HEROES[rel]) body = heroFigure(HEROES[rel], depth) + body

  const dest = join(OUT, rel)
  await mkdir(dirname(dest), { recursive: true })
  await writeFile(dest, frontmatter ? `---\n${frontmatter}\n---\n${body}` : body)
  written.add(rel)
}

// The site's own landing page, kept in this repo rather than the vault. Its
// `hero:` frontmatter key names a plate the same way HEROES does for vault pages.
let home = await readFile(join(import.meta.dirname, "site-home.md"), "utf8")
const homeHero = home.match(/^hero:\s*(\S+)\s*$/m)
if (homeHero) {
  home = home.replace(/^hero:.*\n/m, "")
  home = home.replace(/^(---\n[\s\S]*?\n---\n)/, `$1\n${heroFigure(homeHero[1], 0)}`)
}
await writeFile(join(OUT, "index.md"), home)
written.add("index.md")

// Curated folder pages. Quartz auto-generates a listing page for every
// directory ("Folder: classes/media-studies/lesson-plans" with raw slugs); these
// index files give each one a real title and a line of context instead. The
// child listing still renders below the body.
const folderIndexes = {
  classes: {
    title: "All courses",
    body:
      "Every course on this site. Start from a course overview:\n\n" +
      Object.values(COURSES)
        .map((c) => `- [[${c.overview}|${c.name}]]`)
        .join("\n"),
  },
  concepts: {
    title: "Concepts",
    body: "Concept pages used across Media Studies — the place to start when revising.",
  },
  entities: {
    title: "Theorists",
    body: "The theorists studied in Media Studies, one page each.",
  },
  shared: {
    title: "School reference",
    body: "School-wide reference pages that apply to every course.",
  },
}
for (const c of Object.values(COURSES)) {
  folderIndexes[c.dir] = {
    title: `${c.name} · All pages`,
    body: `Everything published for ${c.name}. Start at the [[${c.overview}|course overview]].`,
  }
  folderIndexes[`${c.dir}/lesson-plans`] = {
    title: `${c.name} · Lessons`,
    body: `Every ${c.name} lesson, in teaching order.`,
  }
  folderIndexes[`${c.dir}/unit-plans`] = {
    title: `${c.name} · Units & plans`,
    body: `${c.name} unit pages and semester plans.`,
  }
  folderIndexes[`${c.dir}/assessments`] = {
    title: `${c.name} · Assessments`,
    body: `The ${c.name} assessment register — every graded item with its date and format.`,
  }
}
for (const [dir, page] of Object.entries(folderIndexes)) {
  // Only folders this run actually populated.
  if (![...written].some((rel) => rel.startsWith(dir + "/"))) continue
  const rel = `${dir}/index.md`
  await writeFile(join(OUT, rel), `---\ntitle: "${page.title}"\n---\n${page.body}\n`)
  written.add(rel)
}

// Month-grid calendars, generated from the agenda table (the single source of truth).
// One page per course, plus the combined grid injected into the hub calendar page.
const events = parseAgenda(await readFile(join(VAULT, "calendar.md"), "utf8"))

for (const key of Object.keys(COURSES)) {
  // Detail layer: every graded item from the course's registers, lesson runs from
  // the lesson plans, and unit spans — parsed straight from the vault.
  const detail = await courseDetailEvents(VAULT, COURSES[key].dir)
  const { rel, content } = coursePage(key, events, detail)
  const dest = join(OUT, rel)
  await mkdir(dirname(dest), { recursive: true })
  await writeFile(dest, content)
  written.add(rel)
}

// Inject the combined month view into the hub calendar page, above the text agenda.
const calRel = "calendar.md"
let cal = await readFile(join(OUT, calRel), "utf8")
const courseLinks =
  "**Per-course calendars:** " +
  Object.values(COURSES)
    .map((c) => `[[${c.dir}/course-calendar|${c.name}]]`)
    .join(" · ")
cal = cal.replace(
  /\n(## [^\n]*Agenda)/,
  `\n## Month view\n\n${calendarBlock(events, null)}\n\n${courseLinks}\n\n$1`,
)
await writeFile(join(OUT, calRel), cal)

// The Image-library gallery: one page of every downsampled (public-domain) plate
// — the hand-curated heroes (credits.json) plus the bulk batch from
// library-images.mjs (library-credits.json, absent until it has been run).
let libCredits = {}
try {
  libCredits = JSON.parse(await readFile(join(import.meta.dirname, "library-credits.json"), "utf8"))
} catch {
  /* library-images.mjs not run yet — gallery shows the heroes only */
}
await writeFile(join(OUT, "library.md"), libraryMarkdown(credits, libCredits))
written.add("library.md")

// Inject a structured course map into each overview, replacing the old inline
// "Start here" sentence links. Built from what was actually published, so it
// cannot list a page that doesn't exist.
for (const c of Object.values(COURSES)) {
  const ovRel = c.overview + ".md"
  if (!written.has(ovRel)) continue
  const prefix = c.dir + "/"
  const items = [...written]
    .filter((rel) => rel.startsWith(prefix) && rel !== ovRel)
    .map((rel) => ({
      rel: rel.slice(prefix.length),
      title: pageTitles.get(rel) ?? rel.split("/").pop().replace(/\.md$/, ""),
      unit: lessonUnits.get(rel),
    }))
  const map = courseMapHtml(items, c.dir)
  if (!map) continue
  let ov = await readFile(join(OUT, ovRel), "utf8")
  // The old navigation: a "> **Start here:** …" blockquote of inline links,
  // and the "Semester plans / Assessment registers" blockquote — both now
  // covered by the map's semester cards.
  ov = ov.replace(/^> \*\*Start here:\*\*[^\n]*\n+/m, "")
  ov = ov.replace(/^> \*\*Semester plans:\*\*[^\n]*(?:\n> [^\n]*)*\n+/m, "")
  // Insert before the first H2 — after the intro prose, before the content.
  ov = /^## /m.test(ov) ? ov.replace(/^## /m, `${map}## `) : ov + "\n" + map
  await writeFile(join(OUT, ovRel), ov)
}

// content/ sits under ~/Documents, which is cloud-synced. When this script clears
// the directory, the sync client restores what it just deleted as conflict copies
// ("index 2.md"), and those land in content/ *after* the filter has run — so they
// reach the site unchecked. That is a filter bypass, not just clutter: a conflict
// copy of a withheld page would be published.
//
// Deleting anything this run did not itself write makes content/ exactly the
// filter's output, whatever else tries to appear in it.
const strays = (await walk(OUT)).map((f) => relative(OUT, f)).filter((rel) => !written.has(rel))

for (const rel of strays) await rm(join(OUT, rel))
if (strays.length) {
  console.log(`Removed ${strays.length} stray file(s) not produced by this sync:`)
  for (const rel of strays.slice(0, 5)) console.log(`  ${rel}`)
  if (strays.length > 5) console.log(`  … and ${strays.length - 5} more`)
}

console.log(
  `Published ${published.length} of ${files.length} pages ` +
    `(${files.length - published.length} withheld, ${strippedCount} had sections stripped) ` +
    `+ the site landing page.`,
)
console.log(
  `Reframed for students: ${reframeStats.cached} from cache, ` +
    `${reframeStats.rewritten} rewritten` +
    (reframeStats.kept ? `, ⚠ ${reframeStats.kept} published unreframed` : "") +
    `.`,
)
