#!/usr/bin/env node
// Sync the Courses vault into Quartz's content/ directory, filtered for students.
//
// The vault is teacher-facing: it carries planning notes, unconfirmed dates, and
// internal scheduling rationale. This script is the gate between that and the
// published site. It never writes back to the vault.
//
// Note on the notice rule: assessments must be announced *at least* one week ahead
// (AL Student Guide p.13). It is a floor, so publishing dates early is fine — it
// gives more notice, never less. Early date visibility is never a reason to withhold.

import { readFile, writeFile, mkdir, rm, readdir } from "node:fs/promises"
import { join, relative, dirname } from "node:path"
import { parseAgenda, calendarBlock, coursePage, COURSES } from "./calendar-grid.mjs"
import { courseMapHtml } from "./course-map.mjs"
import { courseDetailEvents } from "./course-events.mjs"

const VAULT = "/Users/dogan/Documents/Vaults/Courses/wiki"
const OUT = join(import.meta.dirname, "content")

// Artwork plates, keyed by page path. Generated by images.mjs from the shared
// Image Slides library; credits.json carries the caption for each.
const HEROES = {
  "calendar.md": "calendar",
  "classes/a-level-art-design/a-level-art-design.md": "a-level-art-design",
  "classes/media-studies/media-studies.md": "media-studies",
  "classes/art-appreciation/art-appreciation.md": "art-appreciation",
  "classes/pre-a-level-art-design/pre-a-level-art-design.md": "pre-a-level-art-design",
  "classes/oxbridge/oxbridge.md": "oxbridge",
  "concepts/representation.md": "representation",
  "classes/art-appreciation/unit-plans/art-appreciation-s1-unit-3-food-the-table-and-ethics.md":
    "the-table",
  "classes/a-level-art-design/unit-plans/9479-s1-unit-2-recording-and-sustained-study.md":
    "observation",
}

const credits = JSON.parse(await readFile(join(import.meta.dirname, "credits.json"), "utf8"))

// Depth-relative path, so the site still works if it's ever served from a subpath.
function heroFigure(slug, depth) {
  const credit = credits[slug]
  if (!credit) return ""
  const prefix = "../".repeat(depth)
  const caption = credit.replace(/\*([^*]+)\*/g, "<em>$1</em>")
  const alt = credit.replace(/\*/g, "")
  return (
    `<figure class="plate plate--hero">\n` +
    `  <img src="${prefix}static/img/${slug}.jpg" alt="${alt}" />\n` +
    `  <figcaption>${caption}</figcaption>\n` +
    `</figure>\n\n`
  )
}

// Pages that never reach students. Paths are relative to the vault's wiki/ root.
const DROP_PAGES = new Set([
  "index.md", // routing table for the LLM, not readers
  "log.md", // append-only operation history
  "courses-dashboard.md", // congestion analysis, risks, open questions
  "shared/first-session-opener.md", // teaching script for the opener
  "shared/image-slide-library.md", // internal 6,181-image asset catalog
  // Every student-relevant date on it already appears on the hub calendar page (a
  // strict superset — verified 2026-07-20); what remains is planning analysis:
  // source-file provenance, correction history, cohort caveats, upstream defects.
  "shared/school-academic-calendar.md",
  "classes/pre-a-level-art-design/lesson-plans/pal-legacy-lesson-library.md", // marked SUPERSEDED
  "classes/pre-a-level-art-design/pal-prior-plans.md", // prior-plans catalog: teacher planning reference (added 2026-07-20)
  "classes/art-appreciation/lesson-plans/art-appreciation-legacy-lesson-bank.md", // prior generation
  "classes/art-appreciation/unit-plans/art-appreciation-food-and-ethics-prior-unit.md", // prior generation
  // The vault's home page is a teacher's dashboard: vault status, the live Bases
  // table, links to the index and dashboard. The site gets site-home.md instead.
  "home.md",
])

// Assessment registers ARE published — students get real value from the per-item
// dates, formats and AO focus. Their internal parts (the "Announced"/"Gap" columns,
// the notice-correction and timetable-redraw callouts, and the trailing rules/
// open-items sections) are stripped by cleanRegister() below. Nothing is withheld
// wholesale by directory anymore.
const DROP_DIRS = []

// H2 sections removed from every page that has them.
const STRIP_SECTIONS = [
  "Teacher notes",
  "Contingencies",
  "Contingencies & open items",
  "Open items",
  "Open items, explained",
  // Assessment-register rule sections: internal scheduling logic, and the general
  // grading rules they restate are already on the published framework page.
  "Applied rules",
  "Notice and marking rules", // "…, as applied"
  "The 13 applied handbook rules", // PAL; heading actually reads "(compact)"
  "Gaps",
  "Image and library needs",
  "Class workspace", // raw/ paths and ingest instructions
  "Holdings", // inventory of source files in raw/
  // Resource-library catalog sections: teacher inventory of raw/ teaching files,
  // with slide counts, an "I cannot watch video" note, and worksheet-as-assessment
  // warnings. The reading sections are kept and cleaned by cleanResourceLibrary().
  "Slide decks",
  "Videos",
  "Worksheets",
  // Course-overview sections that are planning notes about the vault itself:
  // which sources disagree, what is still undecided, what is missing.
  "⚠ Old-spec traps",
  "⚠ The syllabus straddle",
  "Open decisions",
  "Known inconsistencies",
  "Missing from",
  "Flags",
  "Two generations of the course",
  "Teaching materials",
  "Heavy dependence on the shared library",
  "Shared-library touchpoints",
  "Information needed",
  // Unit-page sections added 2026-07-20: teacher mappings of raw/ files to sessions,
  // and prior-year plan mining notes. Both reference raw/ paths and usage guidance.
  "Resources",
  "Prior plan",
  "Course-wide references", // resource-library catalog section (AO guide, elements chart)
]

// Matched as a prefix, so "## Gaps this material does *not* fill" is caught by "Gaps".
// Safe for this list: none of these names begins a student-facing heading.

const isDropped = (rel) =>
  DROP_PAGES.has(rel) || DROP_DIRS.some((d) => rel.includes(d))

async function walk(dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...(await walk(full)))
    else if (entry.name.endsWith(".md")) out.push(full)
  }
  return out
}

// Remove an H2 section: the heading through to the next H2 or end of file.
function stripSections(body) {
  for (const name of STRIP_SECTIONS) {
    const esc = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    // Terminate at the next H2 or end of file. JS has no \z, so the alternative
    // is a negative lookahead for any remaining character.
    body = body.replace(
      new RegExp(`^## ${esc}.*$[\\s\\S]*?(?=^## |(?![\\s\\S]))`, "gm"),
      "",
    )
  }
  return body
}

// Split a markdown table row into cells, respecting `\|` escapes — the registers
// carry `[[path\|alias]]` wikilinks whose pipe must not be read as a column break.
function splitRow(line) {
  const cells = line.split(/(?<!\\)\|/)
  if (cells.length && cells[0].trim() === "") cells.shift()
  if (cells.length && cells[cells.length - 1].trim() === "") cells.pop()
  return cells
}

// Remove named columns from every GitHub-style table in the text. Used to drop the
// internal "Announced" and "Gap" columns while keeping the student-facing ones.
function dropTableColumns(body, dropHeaders) {
  const lines = body.split("\n")
  const out = []
  for (let i = 0; i < lines.length; i++) {
    const sep = lines[i + 1]
    const isTableHead =
      lines[i].includes("|") &&
      sep &&
      /-/.test(sep) &&
      /^\s*\|?[\s:|-]+\|[\s:|-]*$/.test(sep)
    if (!isTableHead) {
      out.push(lines[i])
      continue
    }
    const drop = new Set(
      splitRow(lines[i])
        .map((h, idx) => (dropHeaders.includes(h.trim()) ? idx : -1))
        .filter((idx) => idx >= 0),
    )
    if (drop.size === 0) {
      out.push(lines[i])
      continue
    }
    let j = i
    while (j < lines.length && lines[j].includes("|") && lines[j].trim() !== "") {
      const kept = splitRow(lines[j]).filter((_, idx) => !drop.has(idx))
      out.push("| " + kept.map((c) => c.trim()).join(" | ") + " |")
      j++
    }
    i = j - 1
  }
  return out.join("\n")
}

// The whole-paragraph and sentence-level internal bits that survive the section and
// column strips — announcement scheduling, timetable contingencies, planning stamps.
// Matched by distinctive substrings so the surrounding student-facing prose stays.
const INTERNAL_PARAGRAPHS = [
  "exposed to Foreign Culture Day", // 9479 CS Friday-slip note
  "each derived against", // Art App Majors intro (announcement scheduling)
  "announcements land 14 days ahead", // PAL attainment note
  "CS notice per handbook", // PAL CS note
  "the two remaining courses with the same gap", // 9479 Final cross-course contrast
  // PAL sketchbook (2026-07-20): A5 is now dated (2027-01-06) and publishes via the
  // attainments table + its clean "A5 — the sketchbook" note. Still teacher-only:
  "Sketchbook spot-checks (adopted", // Course Skills spot-checks — cadence still open
  "Format spec exists", // EoT pointer into prior-plans (teacher material)
]

// Register-only cleanup, on top of the shared section strip.
function cleanRegister(body) {
  // Every blockquote in these registers is internal: the notice-rule correction,
  // the "timetable has no Thursday" redraw, and the `> **Codes:**` mapping note.
  body = body.replace(/(?:^>.*(?:\n|$))+/gm, "")

  body = dropTableColumns(body, ["Announced", "Gap"])

  body = body
    .split(/\n\n+/)
    .filter((para) => !INTERNAL_PARAGRAPHS.some((s) => para.includes(s)))
    .join("\n\n")

  // Register-only planning tails. (The "Confirmed by the human" stamp is handled
  // globally by stripStamp, since it appears on many non-register pages too.)
  // These run from their marker to the end of the paragraph and stop at the break,
  // so the following heading survives.
  body = body
    .replace(/[ \t]*\*\*Resolved [^*]*?\.\*\*[ \t]*/g, "")
    .replace(/[ \t]*Open question:[\s\S]*?(?=\n\n|$)/g, "")
    .replace(/[ \t]+\n/g, "\n")

  return body
}

// The vault stamps human-confirmed facts as "Confirmed by the human <date>" (and a
// lowercase "(confirmed <date>)" variant) — an authoring convention, never for
// students. Drop the stamp, keep the fact. Applied to every page.
function stripStamp(body) {
  return body
    // Prefix form "Confirmed by the human <date>: Fact" / "…<date>, Fact" → "Fact".
    .replace(
      /Confirmed by the human 20\d\d-\d\d-\d\d[:,]\s*(\*{0,2})([a-z])/g,
      (_, emph, ch) => emph + ch.toUpperCase(),
    )
    // Standalone / trailing stamp, with any leading comma, semicolon or space.
    .replace(/[,;]?\s*Confirmed by the human 20\d\d-\d\d-\d\d/g, "")
    // Lowercase parenthetical "(confirmed <date>[, …])", incl. "(re-confirmed 07-20)".
    .replace(/\s*\((?:re-?)?confirmed (?:20\d\d-)?\d\d-\d\d[^)]*\)/gi, "")
    // Empty bold left when the stamp was the whole bold span: "**** — a studio…" →
    // "A studio…"; bare "****" → "".
    .replace(/\*\*\s*\*\*\s*—\s*([a-z])/g, (_, ch) => ch.toUpperCase())
    .replace(/\*\*\s*\*\*/g, "")
    .replace(/[ \t]{2,}/g, " ")
    .replace(/[ \t]+([.,;])/g, "$1")
}

// Students see assessments at their real dates (the calendar and the register tables).
// The vault also models when each is *announced* — teacher scheduling that means nothing
// to a student. Strip the announcement notes, keeping the assignment itself. Not applied
// to the framework page, which legitimately explains the one-week notice policy.
function stripAnnouncements(body) {
  return body
    // Parenthetical note that mixes announcement with a return date:
    // "(announced 11-13; returned Tue 12-01)" → "(returned Tue 12-01)".
    .replace(/\(announced [^;)]*;\s*/gi, "(")
    // Announcement-only parenthetical: "(announced 09-30)" / "(announced Tue 12-01)" → "".
    .replace(/\s*\(announced[^)]*\)/gi, "")
    // Clause after a sit date: "sits <date>, announced <date> — see …" → drop the clause.
    // The lookahead leaves the boundary punctuation and any space before it intact, so
    // "sits <date>, announced <date> — see" becomes "sits <date> — see", not "…date— see".
    .replace(/\s*[—,]\s*announced\b[^.;,—|)]*?(?=\s*[.;,—|)]|$)/gi, "")
    // Prose clause "…; announced <date> (reason)…" → drop to the next . ; or cell edge.
    .replace(/;\s*announced\b[^.;|]*?(?=\s*[.;|]|$)/gi, "")
    // Whole bold sentence about announcement: "**A4 is announced on the A3 sitting day**".
    .replace(/\*\*A\d is announced[^*]*\*\*/gi, "")
    // Session-table / inline markers, with an optional leading "·" or ";" separator:
    // "A2 announced", "A1 + CS1 announced", "**A3 announced**", "**CS4** · A4 announced".
    .replace(/(?:\s*[·;]\s*)?\*{0,2}A\d(?:\s*\+\s*CS\d)?\s+announced\*{0,2}/g, "")
    // Register cell note "— announced with A1 on 09-16" and "A4's announcement on 12-16".
    .replace(/\s*—?\s*announced with [^|.\n]*/gi, "")
    .replace(/\s*A\d's announcement on \d\d-\d\d/gi, "")
    // "announced here at U1·L10" / "**announced here**" and bare "announced here".
    .replace(/\*{0,2}announced here\*{0,2}(?:\s+at\s+[^.;|]*)?/gi, "")
    // Register-pointer phrasing on semester/unit pages: keep the pointer, drop the
    // "announcement dates and rules" / "the announcement rule (…)" descriptor.
    .replace(/\s*with (?:the full )?announcement dates and rules/gi, "")
    .replace(/\s*with the announcement rule \([^)]*\)/gi, "")
    // Tidy: empty parens, cell-initial dangling separators, doubled spaces.
    .replace(/\(\s*\)/g, "")
    .replace(/(\|\s*)[;·]\s+/g, "$1")
    .replace(/[ \t]{2,}/g, " ")
    .replace(/[ \t]+([.,;])/g, "$1")
    .replace(/[ \t]+\|/g, " |")
    .replace(/[ \t]+\n/g, "\n")
}

// The resource-library page is a teacher catalog of raw/ files. With its inventory
// sections stripped (Slide decks / Videos / Worksheets / Gaps), what remains is the
// two reading tables — this reframes them as a student reading list: the "teacher
// reference" shelf becomes "Further reading", and the catalog/ingest framing goes.
function cleanResourceLibrary(body) {
  return body
    .replace(/^## Readings — teacher reference\s*$/m, "## Further reading")
    // Framing lines written for the teacher, not the reader.
    .replace(/^Not student-facing\. [^\n]*\n/m, "")
    .replace(/^Confirmed with the human 20\d\d-\d\d-\d\d as student-facing\.\s*\n/m, "")
    .replace(/^Catalog of `raw\/[^\n]*\n/m, "")
    .replace(/^\*\*Catalogued, not transcribed\.\*\* [^\n]*\n/m, "")
    .replace(/^The important thing this drop changes:[^\n]*\n/m, "")
    // Closing line of vault analysis ("assembled for the current arc, not the prior unit").
    .replace(/^Six of the seven map onto lessons[^\n]*\n/m, "")
    .replace(/\n{3,}/g, "\n\n")
}

// The calendar page carries Obsidian-only framing: a pointer to the Full Calendar
// plugin (which doesn't exist on the web) and a vault-maintenance "derived view"
// note. Strip both so the agenda reads as the calendar, not a mirror of one.
function cleanCalendar(body) {
  return body
    .replace(/\s*For the visual month\/week view[\s\S]*?greppable list\./, "")
    .replace(/^This is a \*derived view\*[\s\S]*?needs fixing\.\s*$/m, "")
    .replace(/\n{3,}/g, "\n\n")
}

// Withheld pages whose student-relevant content lives on another published page:
// links to them are retargeted there instead of degrading to plain text.
const LINK_REDIRECTS = {
  // The hub calendar is a strict superset of the school calendar's dates.
  "shared/school-academic-calendar": "calendar",
}

// Links to withheld pages are retargeted (if a redirect exists) or become plain
// text, so the site has no dead ends. Handles [[path]], [[path|alias]] and the
// [[path\|alias]] form used inside tables.
function derefDropped(text, publishedTargets) {
  return text.replace(/\[\[([^\]|]+?)(?:(\\?\|)([^\]]*?))?\]\]/g, (match, target, pipe, alias) => {
    const clean = target.split("#")[0].trim()
    if (publishedTargets.has(clean)) return match
    // Humanize the slug for bare links, so prose reads "the school academic
    // calendar", not "the school-academic-calendar".
    const label = alias ?? clean.split("/").pop().replace(/-/g, " ")
    const redirect = LINK_REDIRECTS[clean]
    if (redirect) return `[[${redirect}${pipe ?? "|"}${label}]]`
    return label
  })
}

// Drop `sources:` (raw/ paths are internal) and prune `related:` of withheld pages.
function cleanFrontmatter(fm, publishedTargets) {
  const lines = fm.split("\n")
  const kept = []
  let inSources = false
  for (const line of lines) {
    if (/^sources:/.test(line)) {
      inSources = true
      continue
    }
    if (inSources) {
      if (/^\s+-\s/.test(line)) continue
      inSources = false
    }
    // Prune related: entries whose target is withheld.
    const relatedEntry = line.match(/^\s+-\s+"\[\[([^\]|]+?)(?:\|[^\]]*)?\]\]"\s*$/)
    if (relatedEntry && !publishedTargets.has(relatedEntry[1].split("#")[0].trim())) continue
    // content/ is regenerated on every sync, so filesystem mtimes are meaningless.
    // The vault's own last_updated is the honest date; Quartz reads `modified`.
    kept.push(line.replace(/^last_updated:/, "modified:"))
  }
  return kept.join("\n")
}

const files = await walk(VAULT)
const published = files
  .map((f) => relative(VAULT, f))
  .filter((rel) => !isDropped(rel))

// Wikilinks in this vault use full vault-relative paths without the .md suffix.
const publishedTargets = new Set(published.map((rel) => rel.replace(/\.md$/, "")))

await rm(OUT, { recursive: true, force: true })
await mkdir(OUT, { recursive: true })

// Every path this run writes, so anything else in content/ can be pruned at the end.
const written = new Set()
// rel → frontmatter title, for the course maps and nav labels.
const pageTitles = new Map()
let strippedCount = 0
for (const rel of published) {
  let raw = await readFile(join(VAULT, rel), "utf8")

  const fmMatch = raw.match(/^---\n([\s\S]*?)\n---\n/)
  let frontmatter = ""
  let body = raw
  if (fmMatch) {
    frontmatter = cleanFrontmatter(fmMatch[1], publishedTargets)
    body = raw.slice(fmMatch[0].length)
    const t = fmMatch[1].match(/^title:\s*"?(.+?)"?\s*$/m)
    if (t) pageTitles.set(rel, t[1])
  }

  const before = body.length
  body = stripSections(body)
  if (rel.includes("/assessments/")) body = cleanRegister(body)
  if (rel.endsWith("resource-library.md")) body = cleanResourceLibrary(body)
  if (rel === "calendar.md") body = cleanCalendar(body)
  body = stripStamp(body)
  // The framework page explains the one-week notice policy — student-useful, keep it.
  if (rel !== "shared/bnds-assessment-framework.md") body = stripAnnouncements(body)
  if (body.length !== before) strippedCount++

  // The Bases plugin embed can't render outside Obsidian.
  body = body.replace(/^!\[\[dashboard\.base\]\]\s*$/gm, "")

  body = derefDropped(body, publishedTargets)
  body = body.replace(/\n{3,}/g, "\n\n").trimEnd() + "\n"

  if (HEROES[rel]) body = heroFigure(HEROES[rel], rel.split("/").length - 1) + body

  const dest = join(OUT, rel)
  await mkdir(dirname(dest), { recursive: true })
  await writeFile(dest, frontmatter ? `---\n${frontmatter}\n---\n${body}` : body)
  written.add(rel)
}

// The site's own landing page, kept in this repo rather than the vault. Its
// `hero:` frontmatter key names a plate the same way HEROES does for vault pages.
let home = await readFile(join(import.meta.dirname, "site-home.md"), "utf8")
const homeHero = home.match(/^hero:\s*(\S+)\s*$/m)
if (homeHero) {
  home = home.replace(/^hero:.*\n/m, "")
  home = home.replace(/^(---\n[\s\S]*?\n---\n)/, `$1\n${heroFigure(homeHero[1], 0)}`)
}
await writeFile(join(OUT, "index.md"), home)
written.add("index.md")

// Month-grid calendars, generated from the agenda table (the single source of truth).
// One page per course, plus the combined grid injected into the hub calendar page.
const events = parseAgenda(await readFile(join(VAULT, "calendar.md"), "utf8"))

for (const key of Object.keys(COURSES)) {
  // Detail layer: every graded item from the course's registers, lesson runs from
  // the lesson plans, and unit spans — parsed straight from the vault.
  const detail = await courseDetailEvents(VAULT, COURSES[key].dir)
  const { rel, content } = coursePage(key, events, detail)
  const dest = join(OUT, rel)
  await mkdir(dirname(dest), { recursive: true })
  await writeFile(dest, content)
  written.add(rel)
}

// Inject the combined month view into the hub calendar page, above the text agenda.
const calRel = "calendar.md"
let cal = await readFile(join(OUT, calRel), "utf8")
const courseLinks =
  "**Per-course calendars:** " +
  Object.values(COURSES)
    .map((c) => `[[${c.dir}/course-calendar|${c.name}]]`)
    .join(" · ")
cal = cal.replace(
  /\n(## [^\n]*Agenda)/,
  `\n## Month view\n\n${calendarBlock(events, null)}\n\n${courseLinks}\n\n$1`,
)
await writeFile(join(OUT, calRel), cal)

// Inject a structured course map into each overview, replacing the old inline
// "Start here" sentence links. Built from what was actually published, so it
// cannot list a page that doesn't exist.
for (const c of Object.values(COURSES)) {
  const ovRel = c.overview + ".md"
  if (!written.has(ovRel)) continue
  const prefix = c.dir + "/"
  const items = [...written]
    .filter((rel) => rel.startsWith(prefix) && rel !== ovRel)
    .map((rel) => ({
      rel: rel.slice(prefix.length),
      title: pageTitles.get(rel) ?? rel.split("/").pop().replace(/\.md$/, ""),
    }))
  const map = courseMapHtml(items, c.dir)
  if (!map) continue
  let ov = await readFile(join(OUT, ovRel), "utf8")
  // The old navigation: a "> **Start here:** …" blockquote of inline links.
  ov = ov.replace(/^> \*\*Start here:\*\*[^\n]*\n+/m, "")
  // Insert before the first H2 — after the intro prose, before the content.
  ov = /^## /m.test(ov) ? ov.replace(/^## /m, `${map}## `) : ov + "\n" + map
  await writeFile(join(OUT, ovRel), ov)
}

// content/ sits under ~/Documents, which is cloud-synced. When this script clears
// the directory, the sync client restores what it just deleted as conflict copies
// ("index 2.md"), and those land in content/ *after* the filter has run — so they
// reach the site unchecked. That is a filter bypass, not just clutter: a conflict
// copy of a withheld page would be published.
//
// Deleting anything this run did not itself write makes content/ exactly the
// filter's output, whatever else tries to appear in it.
const strays = (await walk(OUT))
  .map((f) => relative(OUT, f))
  .filter((rel) => !written.has(rel))

for (const rel of strays) await rm(join(OUT, rel))
if (strays.length) {
  console.log(`Removed ${strays.length} stray file(s) not produced by this sync:`)
  for (const rel of strays.slice(0, 5)) console.log(`  ${rel}`)
  if (strays.length > 5) console.log(`  … and ${strays.length - 5} more`)
}

console.log(
  `Published ${published.length} of ${files.length} pages ` +
    `(${files.length - published.length} withheld, ${strippedCount} had sections stripped) ` +
    `+ the site landing page.`,
)
