#!/usr/bin/env node
// Sync the Courses vault into Quartz's content/ directory, filtered and
// reframed for students.
//
// The vault is teacher-facing: it carries planning notes, unconfirmed dates, and
// internal scheduling rationale. This script is the gate between that and the
// published site. It never writes back to the vault.
//
// Two stages: the deterministic filter below (the privacy gate — drops pages,
// strips sections, removes stamps) runs first; then reframe.mjs rewrites each
// surviving page into student-facing voice via the Claude API, cached by
// content hash in reframe-cache.json. Requires ANTHROPIC_API_KEY (or an
// `ant auth login` profile) when pages have changed; REFRAME=off skips the
// model and publishes filter-only output with a warning.
//
// Note on the notice rule: assessments must be announced *at least* one week ahead
// (AL Student Guide p.13). It is a floor, so publishing dates early is fine — it
// gives more notice, never less. Early date visibility is never a reason to withhold.

import { readFile, writeFile, mkdir, rm, readdir } from "node:fs/promises"
import { join, relative, dirname } from "node:path"
import { parseAgenda, calendarBlock, coursePage, COURSES } from "./calendar-grid.mjs"
import { courseMapHtml } from "./course-map.mjs"
import { courseDetailEvents } from "./course-events.mjs"
import { reframeAll } from "./reframe.mjs"
import { libraryMarkdown } from "./gallery.mjs"
import { insertCitations } from "./cite.mjs"
import { checkDates, PAPER, PAPER_BEFORE } from "./date-check.mjs"
import { syncDecks, deckLine, courseDeckBlock, DECKS_DIR } from "./decks.mjs"
import { statStrip, stripHtml } from "./at-a-glance.mjs"

// Env overrides exist so the pipeline can be exercised off-machine against a
// fixture vault without touching the real content/. Normal use needs neither.
const VAULT = process.env.VAULT ?? "/Users/dogan/Documents/Vaults/Courses/wiki"
const OUT = process.env.OUT ?? join(import.meta.dirname, "content")

// Artwork plates, keyed by page path. Generated by images.mjs from the shared
// Image Slides library; credits.json carries the caption for each.
const HEROES = {
  "calendar.md": "calendar",
  "classes/a-level-art-design/a-level-art-design.md": "a-level-art-design",
  "classes/media-studies/media-studies.md": "media-studies",
  "classes/art-appreciation/art-appreciation.md": "art-appreciation",
  "classes/pre-a-level-art-design/pre-a-level-art-design.md": "pre-a-level-art-design",
  "classes/oxbridge/oxbridge.md": "oxbridge",
  "concepts/representation.md": "representation",
  "classes/art-appreciation/unit-plans/art-appreciation-s1-unit-3-food-the-table-and-ethics.md":
    "the-table",
  "classes/a-level-art-design/unit-plans/9479-s1-unit-2-recording-and-sustained-study.md":
    "observation",
  // ── Unit heroes (banner per unit; pipeline-stage / theme signatures) ────────
  // A Level S1 (C1 Portfolio)
  "classes/a-level-art-design/unit-plans/9479-s1-unit-1-foundations-on-the-theme.md":
    "banqueting-sketch",
  "classes/a-level-art-design/unit-plans/9479-s1-unit-3-exploration-and-artist-study.md":
    "mark-making",
  "classes/a-level-art-design/unit-plans/9479-s1-unit-4-development.md": "composition",
  "classes/a-level-art-design/unit-plans/9479-s1-unit-5-final-outcome-and-portfolio.md":
    "cafe-terrace",
  // A Level S2 (C3 part 1) — same stages, varied plates
  "classes/a-level-art-design/unit-plans/9479-s2-unit-1-foundations-on-the-investigation.md":
    "first-marks",
  "classes/a-level-art-design/unit-plans/9479-s2-unit-2-recording-and-sustained-study.md":
    "drawn-from-life",
  "classes/a-level-art-design/unit-plans/9479-s2-unit-3-exploration-and-artist-study.md":
    "van-gogh-armchair",
  "classes/a-level-art-design/unit-plans/9479-s2-unit-4-development.md": "repin-cossacks-study",
  "classes/a-level-art-design/unit-plans/9479-s2-unit-5-mid-point-portfolio.md": "the-great-wave",
  // A Level S3 (C3 part 2)
  "classes/a-level-art-design/unit-plans/9479-s3-unit-1-review-and-goal-setting.md": "first-marks",
  "classes/a-level-art-design/unit-plans/9479-s3-unit-4-development-second-pass.md":
    "repin-cossacks-study",
  "classes/a-level-art-design/unit-plans/9479-s3-unit-5-final-outcomes.md": "cafe-terrace",
  "classes/a-level-art-design/unit-plans/9479-s3-unit-6-assembly-and-submission.md":
    "the-great-wave",
  // A Level S4 (C2 ESA)
  "classes/a-level-art-design/unit-plans/9479-s4-unit-1-foundations-on-the-question.md":
    "banqueting-sketch",
  "classes/a-level-art-design/unit-plans/9479-s4-unit-2-recording.md": "observation",
  "classes/a-level-art-design/unit-plans/9479-s4-unit-3-exploration-and-artist-study.md":
    "mark-making",
  "classes/a-level-art-design/unit-plans/9479-s4-unit-4-development.md": "composition",
  "classes/a-level-art-design/unit-plans/9479-s4-unit-5-supervised-test-and-submission.md":
    "the-great-wave",
  // Art Appreciation S1 (U3 the-table already set above)
  "classes/art-appreciation/unit-plans/art-appreciation-s1-unit-1-origins-and-ancestral-memory.md":
    "deer-mandala",
  "classes/art-appreciation/unit-plans/art-appreciation-s1-unit-2-narrative-myth-and-allegory.md":
    "calling-of-matthew",
  "classes/art-appreciation/unit-plans/art-appreciation-s1-unit-4-images-mediation-and-modernity.md":
    "representation",
  "classes/art-appreciation/unit-plans/art-appreciation-s1-unit-5-semester-close-and-retrospective.md":
    "wanderer",
  // Media Studies S1
  "classes/media-studies/unit-plans/9607-s1-unit-1-introduction.md": "rebel-sharpshooter",
  "classes/media-studies/unit-plans/9607-s1-unit-2-media-language.md": "migrant-mother",
  "classes/media-studies/unit-plans/9607-s1-unit-3-macro-and-textual-analysis.md": "folies-bergere",
  "classes/media-studies/unit-plans/9607-s1-unit-4-representation.md": "kasebier-wild-west",
  "classes/media-studies/unit-plans/9607-s1-unit-5-media-contexts.md": "above-fifth-avenue",
  "classes/media-studies/unit-plans/9607-s1-unit-6-revision-and-consolidation.md": "musicians",
  // Pre A Level S1
  "classes/pre-a-level-art-design/unit-plans/pal-s1-unit-1-drawing-and-the-visual-elements.md":
    "first-marks",
  "classes/pre-a-level-art-design/unit-plans/pal-s1-unit-2-photography.md": "the-great-wave",
  "classes/pre-a-level-art-design/unit-plans/pal-s1-unit-3-collage.md": "lissitzky-schwitters",
  "classes/pre-a-level-art-design/unit-plans/pal-s1-unit-4-graphic-design-and-the-poster.md":
    "mucha-poster",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-01-introduction-the-sketchbook-and-first-marks.md":
    "first-marks",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-02-tone-and-form.md": "tone-and-form",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-03-texture-mark-making-and-negative-space.md":
    "mark-making",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-04-composing-the-final-drawing.md":
    "composition",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-05-a1-the-final-observational-drawing.md":
    "drawn-from-life",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-06-framing-and-viewpoint.md":
    "the-great-wave",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-07-light-shadow-and-the-series-theme.md":
    "lincoln-cathedral",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-08-the-theme-shoot-and-the-contact-sheet-edit.md":
    "articles-of-glass",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-09-a2-the-photographic-series.md":
    "atget-rue-moliere",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-10-juxtaposition-and-scale.md":
    "guitar-gas-jet",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-11-layering-text-and-image.md":
    "lissitzky-schwitters",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-12-theme-and-composition-drafts.md":
    "vanitas",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-13-final-collage-production.md":
    "assembling",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-14-a3-the-final-collage.md":
    "cahun-self-portrait",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-15-the-poster-message-audience-hierarchy.md":
    "mucha-poster",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-16-a4-the-final-poster.md":
    "pioneer-girl",
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-17-the-portfolio-and-the-sketchbook.md":
    "album-leaf",
  "classes/media-studies/lesson-plans/9607-s1-lesson-01-the-four-key-concepts.md":
    "seventh-regiment",
  "classes/media-studies/lesson-plans/9607-s1-lesson-02-semiotics-how-images-mean.md":
    "skull-cigarette",
  "classes/media-studies/lesson-plans/9607-s1-lesson-03-sign-types-and-codes.md":
    "calling-of-matthew",
  "classes/media-studies/lesson-plans/9607-s1-lesson-04-genre-and-camera.md": "at-the-telephone",
  "classes/media-studies/lesson-plans/9607-s1-lesson-05-narrative-and-the-planning-lock.md":
    "banqueting-sketch",
  "classes/media-studies/lesson-plans/9607-s1-lesson-06-a1-timed-media-language-analysis.md":
    "whittier-classroom",
  "classes/media-studies/lesson-plans/9607-s1-lesson-07-reading-systematically-toward-the-blog-midpoint.md":
    "wanderer",
  "classes/media-studies/lesson-plans/9607-s1-lesson-08-representation-applied-to-your-own-product.md":
    "kasebier-wild-west",
  "classes/media-studies/lesson-plans/9607-s1-lesson-09-the-gaze.md": "folies-bergere",
  "classes/media-studies/lesson-plans/9607-s1-lesson-10-the-creative-critical-reflection.md":
    "rivera-self-portrait",
  "classes/media-studies/lesson-plans/9607-s1-lesson-11-audiences-and-the-portfolio-submission.md":
    "good-glass-of-beer",
  "classes/media-studies/lesson-plans/9607-s1-lesson-12-institutions-and-section-a-craft.md":
    "above-fifth-avenue",
  "classes/media-studies/lesson-plans/9607-s1-lesson-13-a4-section-a-in-authentic-format.md":
    "lindbergh-1927",
  "classes/media-studies/lesson-plans/9607-s1-lesson-14-consolidation-and-the-coverage-matrix.md":
    "moon-atlas",
  "classes/media-studies/lesson-plans/9607-s1-lesson-15-exam-rehearsal.md": "musicians",
  "classes/media-studies/lesson-plans/9607-s1-lesson-16-end-of-term-exam-and-return.md":
    "the-magpie",
}

// In-copyright works cited in lessons — named and linked, never embedded (see
// cite.mjs). Same shape as FIGURES (keyed by vault path, injected after the
// paragraph matching `anchor`), but renders a citation line, not an image. Add
// `src` for a "view →" link; omit it for a placeholder. Public-domain works go
// through FIGURES/HEROES as actual images instead.
const CITATIONS = {
  "classes/media-studies/lesson-plans/9607-s1-lesson-09-the-gaze.md": [
    { cite: "Cindy Sherman, *Untitled Film Still #21*, 1978", anchor: /three looks/i },
  ],
}

// Inline figures (2026-07-21): lesson pages carry period exemplars from the shared
// library, inserted after the paragraph that first matches `anchor`. Anchors are
// content facts rather than headings, chosen to survive the reframe stage; an
// unmatched figure lands at the end of the body instead of vanishing, so the git
// diff of content/ shows exactly where each one settled. Entries with several
// slugs render side by side as a .plate-row grid.
const FIGURES = {
  // ── Art Appreciation S1 (period exemplars, one per lesson) ────────────────
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-01-opening-the-atlas.md": [
    { slugs: ["articles-of-glass"], anchor: /physical trace|light did to a surface/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-02-what-survives-and-why.md": [
    {
      slugs: ["mummy-portrait"],
      anchor: /the wall is the evidence|what had to happen for an object to reach you/i,
    },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-03-the-first-board.md": [
    { slugs: ["deer-mandala"], anchor: /ritual objects and ancestral presence/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-04-telling-it-without-words.md":
    [{ slugs: ["calling-of-matthew"], anchor: /where a still image puts time/i }],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-05-titian-to-manet.md": [
    { slugs: ["folies-bergere"], anchor: /refusals Manet is making|Manet, \*Olympia\*/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-06-the-table-as-moral-space.md":
    [{ slugs: ["the-table"], anchor: /three paintings of meals|who is where/i }],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-07-the-split-weeks.md": [
    { slugs: ["composition"], anchor: /your own table/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-08-heda-and-the-image-of-work.md":
    [{ slugs: ["heda-still-life"], anchor: /the still life as inventory/i }],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-09-food-the-table-and-ethics.md":
    [
      {
        slugs: ["last-supper"],
        anchor: /one claim about food and ethics|food and ethics, argued from the pictures/i,
      },
    ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-10-berger-and-the-reproduction.md":
    [{ slugs: ["the-magpie"], anchor: /a reproduction is not a neutral copy/i }],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-11-aura-and-the-poor-image.md":
    [{ slugs: ["representation"], anchor: /a print is many/i }],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-12-photography-and-after.md": [
    {
      slugs: ["the-great-wave"],
      anchor: /why we believe photographs|photography and the claim to truth/i,
    },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-13-the-artworld-and-the-brief.md":
    [
      {
        slugs: ["guitar-gas-jet"],
        anchor:
          /the artworld and the end of art|what makes something art when looking cannot tell you/i,
      },
    ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-14-the-retrospective.md": [
    { slugs: ["album-leaf"], anchor: /read back as one argument/i },
  ],
  "classes/art-appreciation/lesson-plans/art-appreciation-s1-lesson-15-return.md": [
    { slugs: ["wanderer"], anchor: /Semester 2 trailer|re-read their own work/i },
  ],
  // ── A Level Art & Design S1 (C1 Portfolio) — one artwork per pipeline stage ──
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-01-introduction-and-the-theme-menu.md": [
    {
      slugs: ["a-level-art-design"],
      anchor: /top-band portfolio|committed to one theme|theme menu/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-02-formal-elements-on-the-theme.md": [
    { slugs: ["mark-making"], anchor: /five different instruments|each formal element/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-03-intention-and-composition-planning.md":
    [
      {
        slugs: ["banqueting-sketch"],
        anchor: /the theme becomes an investigation|composition planning/i,
      },
    ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-04-the-sustained-study.md": [
    { slugs: ["observation"], anchor: /One long observed study|the spine of AO1|Stage 1 page/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-05-recording-pages-and-a1.md": [
    // "pages an examiner…" broke when prompt v3 started bolding **recording
    // pages** mid-phrase; anchor on the bold-free tail instead.
    { slugs: ["drawn-from-life"], anchor: /examiner could read/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-06-media-exploration.md": [
    {
      slugs: ["repin-nevsky-studies"],
      anchor: /twelve prescribed experiments|which media carry the theme/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-07-selection-and-scale.md": [
    { slugs: ["tone-and-form"], anchor: /select your media|the exploration becomes a commitment/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-08-artist-study-1.md": [
    { slugs: ["van-gogh-armchair"], anchor: /they solve the problem in your work|first artist/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-09-artist-2-bridge-piece-and-a2.md": [
    {
      slugs: ["repin-cossacks-study"],
      anchor: /second artist against the first|from study into develop/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-10-composition-1.md": [
    { slugs: ["composition"], anchor: /from your own recorded studies|never from memory/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-11-composition-2-and-critique.md": [
    { slugs: ["vanitas"], anchor: /the alternative you did not take|built with the same effort/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-12-targeted-tests-and-direction.md": [
    { slugs: ["skull-cigarette"], anchor: /what the critique left unresolved|targeted tests/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-13-final-plan-and-a3.md": [
    { slugs: ["van-gogh-outskirts"], anchor: /solved small|palette and materials are settled/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-14-the-final-outcome.md": [
    { slugs: ["cafe-terrace"], anchor: /one continuous run|underdrawing through to surface/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s1-lesson-15-submission-week-and-a4.md": [
    { slugs: ["the-great-wave"], anchor: /the photograph is the version the examiner sees/i },
  ],
  // ── A Level Art & Design S2 (C3 Personal Investigation) — same stage signatures ──
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-01-opening-the-investigation.md": [
    {
      slugs: ["first-marks"],
      anchor: /read a 90\/100 investigation|propose the theme yourself|most consequential/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-02-proposal-and-feasibility.md": [
    {
      slugs: ["banqueting-sketch"],
      anchor: /stress-test the whole thing|a proposal you can defend/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-03-theme-locked.md": [
    { slugs: ["a-level-art-design"], anchor: /lock it in writing|no restarts/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-04-recording-and-the-a1-milestone.md": [
    {
      slugs: ["drawn-from-life"],
      anchor: /makes your thinking visible to a stranger|one sustained study/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-05-recording-pages-and-feedback.md": [
    {
      slugs: ["repin-nevsky-studies"],
      anchor: /three specific actions|build the recording pages/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-06-media-exploration.md": [
    { slugs: ["mark-making"], anchor: /twelve media experiments|experiments built so they/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-07-artist-1-in-full.md": [
    {
      slugs: ["van-gogh-armchair"],
      anchor: /an artist who solves the problem|copy to understand/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-08-artist-2-bridge-and-a2.md": [
    {
      slugs: ["repin-cossacks-study"],
      anchor: /a different angle on the same problem|the bridge piece/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-09-composition-1.md": [
    { slugs: ["composition"], anchor: /from your own studies|hold one idea across two/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-10-resolving-composition-1.md": [
    { slugs: ["tone-and-form"], anchor: /Unresolved work cannot be judged|resolve composition 1/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-11-composition-2-and-paper-drafts.md": [
    { slugs: ["vanitas"], anchor: /the rejected alternative|equal effort/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-12-critique-and-targeted-tests.md": [
    { slugs: ["skull-cigarette"], anchor: /only what is unresolved|choosing is development/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-13-evaluation-draft-1-and-a3.md": [
    {
      slugs: ["van-gogh-outskirts"],
      anchor: /against your intention, not the effort|trail of decisions/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-14-mid-point-piece-and-bibliography.md": [
    {
      slugs: ["observation"],
      anchor: /choose the piece that carries the investigation|into the body of the work/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s2-lesson-15-submission-week-and-a4.md": [
    { slugs: ["the-great-wave"], anchor: /the photograph is the version the examiner sees/i },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-01-reopening-and-the-summer-audit.md": [
    {
      slugs: ["rivera-self-portrait"],
      anchor:
        /the job is to know exactly where it stands|judged honestly against the target set for it in June/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-02-the-action-plan-and-development-resumes.md":
    [
      {
        slugs: ["repin-cossacks-study"],
        anchor:
          /compose final-outcome candidates from the summer production|the semester's contract/i,
      },
    ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-03-candidate-compositions-and-the-paper-reopens.md":
    [
      {
        slugs: ["repin-nevsky-studies"],
        anchor:
          /a single idea can't be compared|both are developed to the same standard so the eventual decision/i,
      },
    ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-04-development-studies-and-targeted-tests.md":
    [
      {
        slugs: ["mark-making"],
        anchor: /run on only what is still unresolved|Development that decides things/i,
      },
    ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-05-evaluation-and-the-national-day-break.md":
    [
      {
        slugs: ["vanitas"],
        anchor:
          /carry it across the National Day break intact|the chosen candidate is brought up to standard before the break/i,
      },
    ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-06-a1-the-development-milestone.md": [
    {
      slugs: ["tone-and-form"],
      anchor:
        /the close of the development second pass|three specific actions to carry into Unit 5/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-07-outcome-1-opens-and-a2-the-mock-review.md":
    [
      {
        slugs: ["album-leaf"],
        anchor:
          /before the Seniors. Days remove all of next week|the whole investigation gets its/i,
      },
    ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-08-building-outcome-1.md": [
    {
      slugs: ["cafe-terrace"],
      anchor: /the sustained build of final outcome 1|what it names, you act on the same day/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-09-resolving-outcome-1-and-the-final-paper-text.md":
    [
      {
        slugs: ["van-gogh-outskirts"],
        anchor:
          /Finish outcome 1 to the standard the examiner will see|confirming every claim points at real work/i,
      },
    ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-10-a3-the-research-paper-and-outcome-2-opens.md":
    [
      {
        slugs: ["rubens-title-page"],
        anchor:
          /The research paper is done, and the second outcome begins|The two outcomes stay inside one investigation/i,
      },
    ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-11-outcome-2-resolved-and-both-evaluated.md":
    [
      {
        slugs: ["impossible-bouquet"],
        anchor: /Bring outcome 2 to the same finish as outcome 1|then judge the pair/i,
      },
    ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-12-assembly-sequence-documentation-bibliography.md":
    [
      {
        slugs: ["assembling"],
        anchor:
          /What the sequence exposes as a gap gets repaired before the critique|its documentation is verified page by page/i,
      },
    ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-13-the-viva-rehearsal-critique.md": [
    {
      slugs: ["musicians"],
      anchor:
        /The dress rehearsal for the submission and for any interview|change what broke, log what held/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-14-a4-the-complete-investigation.md": [
    {
      slugs: ["the-great-wave"],
      anchor:
        /The Component 3 internal submission|Submission photography begins while the work is at hand/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s3-lesson-15-submission-qc-the-return-and-into-c2.md":
    [
      {
        slugs: ["album-leaf"],
        anchor:
          /Close Component 3 and turn toward Component 2|assemble the PDF to the Cambridge screen limits/i,
      },
    ],
  "classes/a-level-art-design/lesson-plans/9479-s4-lesson-01-the-esa-question-locked.md": [
    {
      slugs: ["first-marks"],
      anchor:
        /Component 2 opens on the Cambridge paper itself|the decision is made against evidence/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s4-lesson-02-recording-at-exam-pace.md": [
    {
      slugs: ["drawn-from-life"],
      anchor:
        /Annotation ties every page back to the question|An intention is stated on the locked question/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s4-lesson-03-sustained-study-and-a1.md": [
    {
      slugs: ["tone-and-form"],
      anchor: /the pages are built so AO1 is obvious without explanation|The recording milestone/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s4-lesson-04-exploration-and-artist-1.md": [
    {
      slugs: ["mark-making"],
      anchor: /Citation without response earns nothing here|A1 feedback becomes targets/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s4-lesson-05-artist-2-the-bridge-piece-and-a2.md": [
    {
      slugs: ["kahnweiler"],
      anchor:
        /Close exploration and carry it into development|surfaces problems now, not in the test room/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s4-lesson-06-development-and-a3-the-content-close.md":
    [
      {
        slugs: ["repin-cossacks-study"],
        anchor: /the point after which nothing new is taught|The tightest unit in the course/i,
      },
    ],
  "classes/a-level-art-design/lesson-plans/9479-s4-lesson-07-the-15-hour-supervised-test.md": [
    {
      slugs: ["sea-of-steps"],
      anchor:
        /the elastic days before the test go to refinement and rehearsal|because content closed at A3/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s4-lesson-08-assembly-and-a4-the-submission-package.md":
    [
      {
        slugs: ["the-great-wave"],
        anchor:
          /Turn the test piece into a submission|so A4 grades the packaging and completeness/i,
      },
    ],
  "classes/a-level-art-design/lesson-plans/9479-s4-lesson-09-board-week-handover-and-records.md": [
    {
      slugs: ["assembling"],
      anchor: /The component leaves the building|the record has to survive the submission/i,
    },
  ],
  "classes/a-level-art-design/lesson-plans/9479-s4-lesson-10-course-close-and-the-two-year-review.md":
    [
      {
        slugs: ["the-magpie"],
        anchor: /The last session of the two-year course|It is a close, not a new unit/i,
      },
    ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-06-framing-and-viewpoint.md": [
    {
      slugs: ["sea-of-steps", "st-pauls-spires", "canon-de-chelle"],
      anchor: /vantage point|rule of thirds/i,
    },
  ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-07-light-shadow-and-the-series-theme.md":
    [
      {
        slugs: ["girl-with-washington", "kasebier-portrait", "the-tugboat"],
        anchor: /diffused/i,
      },
      { slugs: ["cloud-sequence"], anchor: /Ueda|one subject, idea, or rule/i },
    ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-08-the-theme-shoot-and-the-contact-sheet-edit.md":
    [
      {
        slugs: ["yosemite-mosquito-camp", "yosemite-rocky-ford"],
        anchor: /everything small|contact sheet:/i,
      },
    ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-09-a2-the-photographic-series.md": [
    {
      slugs: ["atget-rue-mazet", "atget-avenue-de-suffren", "atget-rue-mazarine"],
      anchor: /take any one image away|kill-your-darlings/i,
    },
    { slugs: ["yosemite-fall"], anchor: /opener/i },
  ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-10-juxtaposition-and-scale.md": [
    { slugs: ["kahnweiler"], anchor: /glue newspaper|papier collé/i },
  ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-11-layering-text-and-image.md": [
    {
      slugs: ["talbot-lace", "rubens-title-page"],
      anchor: /torn edge|transparency/i,
    },
  ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-12-theme-and-composition-drafts.md": [
    { slugs: ["impossible-bouquet"], anchor: /vanitas|none of this lasts/i },
  ],
  "classes/pre-a-level-art-design/lesson-plans/pal-s1-lesson-15-the-poster-message-audience-hierarchy.md":
    [
      {
        slugs: ["gsell-advertisement", "kawase-temple"],
        anchor: /name card|Ukiyo-e|first read/i,
      },
    ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-01-the-four-key-concepts.md": [
    {
      // Target the D2 mediation-demo list, not the Goal paragraph (which also
      // says "a version, not a window"). "Anchorage" is the list's last bullet,
      // so the pair lands after the three mechanisms.
      slugs: ["rebel-sharpshooter", "migrant-mother"],
      anchor: /- \*\*Anchorage\*\*/,
    },
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-02-semiotics-how-images-mean.md": [
    { slugs: ["mummy-portrait"], anchor: /connotation chains|who taught you that/i },
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-03-sign-types-and-codes.md": [
    {
      slugs: ["nadar-taylor", "talbot-lace-index", "deer-mandala"],
      anchor: /an index that looks like an icon|means by convention/i,
    },
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-04-genre-and-camera.md": [
    {
      // The v3 restructure dropped the skulls-and-candles starter; the pair now
      // illustrates Neale directly (its captions say so).
      slugs: ["vanitas-schaak", "vanitas-schoor"],
      anchor: /difference in repetition|repetition and difference/i,
    },
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-05-narrative-and-the-planning-lock.md": [
    { slugs: ["peasant-wedding"], anchor: /by what they do, not who they are|donor/i },
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-06-a1-timed-media-language-analysis.md": [
    {
      slugs: ["vivarini-exorcism"],
      anchor: /where did Propp fail|withheld function/i,
    },
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-07-reading-systematically-toward-the-blog-midpoint.md":
    [
      {
        // v3 writes the protocol as prose ("describe, question, suggest"), not
        // the arrow chain the old anchor matched.
        slugs: ["hampton-geography"],
        anchor: /describe, question, suggest|audited post by post/i,
      },
    ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-08-representation-applied-to-your-own-product.md":
    [{ slugs: ["lincoln-mcclellan"], anchor: /photo-op is older than the word|posed in a tent/i }],
  "classes/media-studies/lesson-plans/9607-s1-lesson-09-the-gaze.md": [
    { slugs: ["cahun-gaze"], anchor: /oppositional gaze|looking back at a text/i },
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-12-institutions-and-section-a-craft.md": [
    {
      slugs: ["emperors-table"],
      anchor: /frame belonged to the payer|imperial commission|Emperor's camp/i,
    },
  ],
}

// Downloadable handout PDFs (2026-07-24), staged under quartz/static/handouts/
// and injected as a download line after `anchor`. The site is password-gated and
// students-only, and the school has licensed the materials. Same keyed-by-vault-
// path shape as FIGURES; vault bodies are untouched, so no reframe is triggered.
const HANDOUTS = {
  "classes/art-appreciation/unit-plans/art-appreciation-s1-unit-3-food-the-table-and-ethics.md": {
    dir: "art-appreciation",
    anchor: /Lesson 6 — Hyperreality/,
    items: [
      { label: "Eat Drink Man Woman", file: "eat-drink-man-woman" },
      { label: "Heda and Still Life", file: "heda-and-still-life" },
      { label: "The Shared Meal", file: "the-shared-meal" },
      { label: "The Moral Image of Work", file: "the-moral-image-of-work" },
      { label: "Martha Rosler Intro", file: "martha-rosler-intro" },
      { label: "Semiotics of the Kitchen", file: "semiotics-of-the-kitchen" },
      { label: "Hyperreality + Paratheatre", file: "hyperreality-and-paratheatre" },
      { label: "Lunch and discussion", file: "lunch-and-discussion" },
      { label: "Culinary Aesthetics", file: "culinary-aesthetics" },
    ],
  },
  // The C1 study guide: one self-contained interactive page covering the whole
  // component, sitting under the At-a-glance table where a student looks for the
  // task's materials. Anchored on the table's last row, so it lands between the
  // table and "## Objectives"; a miss degrades to a link at the foot of the page.
  "classes/media-studies/assessments/9607-s1-a3-c1-portfolio.md": {
    dir: "media-studies",
    title: "Study guide:",
    anchor: /\| Unit \|/,
    items: [
      {
        label: "Component 1: the Foundation Portfolio (interactive)",
        file: "c1-foundation-portfolio",
        ext: "html",
      },
    ],
  },
  "classes/pre-a-level-art-design/pal-resource-library.md": {
    dir: "pre-a-level-art-design",
    title: "Worksheets & guides (PDF):",
    anchor: /Color mixing guide|wavelength spectrum/,
    items: [
      { label: "Drawing Basics", file: "drawing-basics" },
      { label: "AO Guide", file: "ao-guide" },
      { label: "Intro to Photography — Vocabulary", file: "photography-vocabulary" },
      { label: "Photography — Exposure (slides)", file: "photography-exposure" },
      { label: "Photography — Digital Workspace (slides)", file: "photography-digital-workspace" },
      { label: "Photography — Websites", file: "photography-websites" },
      { label: "Collage — Instructions", file: "collage-instructions" },
      { label: "Collage — Presentation (slides)", file: "collage-presentation" },
      { label: "Carving Step by Step", file: "carving-step-by-step" },
    ],
  },
}

const credits = JSON.parse(await readFile(join(import.meta.dirname, "credits.json"), "utf8"))

// Depth-relative path, so the site still works if it's ever served from a subpath.
function figureHtml(slug, depth, cls = "plate") {
  const credit = credits[slug]
  if (!credit) return ""
  const prefix = "../".repeat(depth)
  const caption = credit.replace(/\*([^*]+)\*/g, "<em>$1</em>")
  const alt = credit.replace(/\*/g, "")
  return (
    `<figure class="${cls}">\n` +
    `  <img src="${prefix}static/img/${slug}.jpg" alt="${alt}" loading="lazy" />\n` +
    `  <figcaption>${caption}</figcaption>\n` +
    `</figure>\n`
  )
}

const heroFigure = (slug, depth) => {
  const html = figureHtml(slug, depth, "plate plate--hero")
  return html && html + "\n"
}

// A FIGURES entry rendered to HTML: one figure, or several in a .plate-row grid.
function figureBlock(slugs, depth) {
  const figs = slugs.map((s) => figureHtml(s, depth)).filter(Boolean)
  if (!figs.length) return ""
  if (figs.length === 1) return figs[0] + "\n"
  return `<div class="plate-row">\n${figs.join("")}</div>\n\n`
}

// Insert each figure after its anchor's first match: directly after the matched
// bullet when the anchor lands inside a list item (splitting the list around the
// figure), otherwise after the containing paragraph; no match → end of the body.
// A download line of handout PDFs, inserted after the paragraph/table matching
// `anchor` (falling back to end of body), mirroring insertFigures.
function insertHandouts(body, entry, depth, rel) {
  const prefix = "../".repeat(depth)
  const links = entry.items
    // Extension defaults to pdf, which every handout was until the 9607 C1 study
    // guide (a self-contained interactive .html) landed 2026-07-31.
    .map(
      (it) =>
        `<a href="${prefix}static/handouts/${entry.dir}/${it.file}.${it.ext ?? "pdf"}">${it.label}</a>`,
    )
    .join(" · ")
  const title = entry.title ?? "Handouts (PDF):"
  // Trailing blank line is load-bearing: an HTML block runs to the next blank
  // line, so without it a following "## Heading" is swallowed into the block and
  // renders as literal text. Only bites when the anchor's paragraph is the last
  // thing before a heading, which the 9607 A3 study guide is.
  const html = `<p class="handouts"><strong>${title}</strong> ${links}</p>\n\n`
  const at = body.search(entry.anchor)
  if (at === -1) {
    if (rel) console.log(`anchor fallback: ${rel} — handouts (${entry.dir})`)
    return body.trimEnd() + "\n\n" + html
  }
  const paraEnd = body.indexOf("\n\n", at)
  const pos = paraEnd === -1 ? -1 : paraEnd + 2
  return pos === -1
    ? body.trimEnd() + "\n\n" + html
    : body.slice(0, pos) + "\n" + html + body.slice(pos)
}

// Tickable checklists, in the same keyed-by-vault-path shape as HANDOUTS: site-authored
// content injected into a vault page, so vault bodies stay untouched and no reframe is
// triggered. Wording is lifted from the C1 study guide's own submission section rather
// than written fresh, so the guide and the page it is linked from agree.
//
// Injected as markdown, not an HTML block, so ObsidianFlavoredMarkdown parses `- [ ]`
// into real checkboxes; only the sub-line is inline HTML, which is parsed normally
// inside a list item (it is *block*-level HTML that swallows to the next blank line).
//
// The storage key checkbox.inline.ts writes is positional — `${slug}-checkbox-${index}`
// across every box on the page in document order. APPEND new items to the end of a list,
// never insert into the middle: inserting shifts every saved tick after it, and a
// student comes back to the wrong boxes ticked.
const CHECKLISTS = {
  "classes/media-studies/assessments/9607-s1-a3-c1-portfolio.md": {
    // Deliberately short: the numbered item directly above already ends "Friday is
    // logistics, not heroics", and repeating it two lines later reads as a stutter.
    lead: "**Run this at the close of the Wednesday session**, not on Friday morning.",
    anchor: /\*\*No edits after\.\*\* This is absolute/,
    items: [
      [
        "Product exported and playable",
        "Open it on a different machine than the one you edited on",
      ],
      ["Reflection posted, in its creative format", "All four questions, embedded and working"],
      [
        "Blog complete, posts dated, contributions labeled",
        "No gaps between the first post and the last",
      ],
      [
        "Every URL checked from a signed-out browser",
        "Including embedded ones. Expired links are the classic failure",
      ],
      ["URLs and files logged on the submission sheet", "Confirmation shown on screen"],
    ],
  },
}

// Mirrors insertHandouts: inserted after the paragraph matching `anchor`, falling back to
// the end of the body if the anchor has drifted.
function insertChecklist(body, entry, rel) {
  // The .ct wrapper is load-bearing: the <li> is a flex container, so every one of its
  // children becomes a column. Without it the sub-line is a sibling of the label and
  // sits beside it rather than under it.
  const list = entry.items
    .map(
      ([label, sub]) => `- [ ] <span class="ct">${label}<span class="ct-sub">${sub}</span></span>`,
    )
    .join("\n")
  const md = `${entry.lead}\n\n${list}\n\n`
  const at = body.search(entry.anchor)
  if (at === -1) {
    if (rel) console.log(`anchor fallback: ${rel} — checklist`)
    return body.trimEnd() + "\n\n" + md
  }
  const paraEnd = body.indexOf("\n\n", at)
  const pos = paraEnd === -1 ? -1 : paraEnd + 2
  return pos === -1 ? body.trimEnd() + "\n\n" + md : body.slice(0, pos) + md + body.slice(pos)
}

// Practice sections (2026-08-03): a vault-authored "## Practice" H2 on lesson
// pages — self-check quizzes and replay activities — travels around the model,
// not through it. Answer keys must survive verbatim, and a quiz edit must not
// invalidate the page's cached rewrite (the cache hashes only the body the
// model sees). Split out here in phase 1, re-appended transformed in phase 3.
function splitPractice(body) {
  const m = body.match(/^## Practice\s*$[\s\S]*?(?=^## |(?![\s\S]))/m)
  if (!m) return { body, practice: "" }
  const rest =
    (body.slice(0, m.index) + body.slice(m.index + m[0].length))
      .replace(/\n{3,}/g, "\n\n")
      .trimEnd() + "\n"
  return { body: rest, practice: m[0].trimEnd() + "\n" }
}

// "> **Answer:** …" blockquotes become tap-to-reveal answers: details/summary
// only, which survives the static Quartz build with no script. The blank lines
// inside the block are load-bearing — the opening <details> tag's HTML block
// ends at the first blank line, so the answer text after it is parsed as
// markdown rather than shipping as literal text inside raw HTML. (Answer bodies
// still must not carry [[wikilinks]]-dependent meaning-critical links; keep
// links in the question lines, where the transformer sees them.)
function practiceDetails(md) {
  return md.replace(/(?:^> .*(?:\n|$))+/gm, (block) => {
    const inner = block.replace(/^> ?/gm, "")
    const m = inner.match(/^\*\*Answer:\*\*\s*([\s\S]*)$/)
    if (!m) return block
    return `<details class="reveal"><summary>Show answer</summary>\n\n${m[1].trimEnd()}\n\n</details>\n`
  })
}

// The deck download line goes directly above the page's first H2 — under the H1
// and its breadcrumb row, where a student looks for the week's materials, and
// above "At a glance". Unlike the handouts it needs no per-page anchor: every
// lesson page has the same shape.
function insertDeckLine(body, html) {
  const at = body.search(/^## /m)
  if (at === -1) return body.trimEnd() + "\n\n" + html
  return body.slice(0, at) + html + "\n" + body.slice(at)
}

function insertFigures(body, entries, depth, rel) {
  for (const entry of entries) {
    const html = figureBlock(entry.slugs, depth)
    if (!html) continue
    const at = body.search(entry.anchor)
    if (at === -1) {
      // Anchor drift. Most drifted anchors were Goal-paragraph phrases that the
      // lesson restructure (prompt v3) folded into "## Overview", so a missed
      // figure lands after the Overview paragraph — the top-of-page position
      // the studio pilot validated — rather than at the page foot. End of body
      // stays the last resort for pages with no Overview. Advisory log, no ⚠:
      // the diff still shows where each figure settled.
      const ov = body.match(/^## Overview[ \t]*\n+/m)
      const ovEnd = ov ? body.indexOf("\n\n", ov.index + ov[0].length) : -1
      if (rel)
        console.log(
          `anchor fallback: ${rel} — figure ${entry.slugs.join(", ")}` +
            (ovEnd !== -1 ? " (after Overview)" : " (end of body)"),
        )
      body =
        ovEnd !== -1
          ? body.slice(0, ovEnd + 2) + "\n" + html + body.slice(ovEnd + 2)
          : body.trimEnd() + "\n\n" + html
      continue
    }
    const lineStart = body.lastIndexOf("\n", at) + 1
    const lineEnd = body.indexOf("\n", at)
    const line = body.slice(lineStart, lineEnd === -1 ? body.length : lineEnd)
    const isBullet = /^\s*- /.test(line)
    let pos
    if (isBullet && lineEnd !== -1) pos = lineEnd + 1
    else {
      const paraEnd = body.indexOf("\n\n", at)
      pos = paraEnd === -1 ? -1 : paraEnd + 2
    }
    body =
      pos === -1
        ? body.trimEnd() + "\n\n" + html
        : body.slice(0, pos) + "\n" + html + body.slice(pos)
  }
  return body
}

// Pages that never reach students. Paths are relative to the vault's wiki/ root.
const DROP_PAGES = new Set([
  "index.md", // routing table for the LLM, not readers
  "log.md", // append-only operation history
  "courses-dashboard.md", // deleted from the vault 2026-07-29 (absorbed into home.md); entry kept harmlessly as a tombstone
  "shared/first-session-opener.md", // teaching script for the opener
  "shared/image-slide-library.md", // internal 6,181-image asset catalog
  // Every student-relevant date on it already appears on the hub calendar page (a
  // strict superset — verified 2026-07-20); what remains is planning analysis:
  // source-file provenance, correction history, cohort caveats, upstream defects.
  "shared/school-academic-calendar.md",
  "classes/pre-a-level-art-design/lesson-plans/pal-legacy-lesson-library.md", // marked SUPERSEDED
  "classes/pre-a-level-art-design/pal-prior-plans.md", // prior-plans catalog: teacher planning reference (added 2026-07-20)
  "classes/art-appreciation/lesson-plans/art-appreciation-legacy-lesson-bank.md", // prior generation
  "classes/art-appreciation/unit-plans/art-appreciation-food-and-ethics-prior-unit.md", // prior generation
  // Provenance analysis, teacher-facing in its entirety: which theorists are
  // Cambridge's vs the centre's, what the vault holds no readings for (2026-07-20).
  "analyses/9607-theory-provenance.md",
  // The S1 engagement layer's own apparatus (both 2026-08-03): the rollout
  // record, and the routine rulebook with its print specs and planted-card
  // teacher keys. What students need of each routine is inline on the lesson
  // pages; links here degrade to plain text via derefDropped.
  "analyses/9607-engagement-revision-plan.md",
  "classes/media-studies/9607-activity-routines.md",
  // Planning history preserved from the deleted courses-dashboard.md (2026-07-29):
  // build waves, congestion risks, resolved decisions — teacher-facing throughout.
  "analyses/summer-2026-buildout.md",
  // The vault's home page is a teacher's dashboard: vault status, the live Bases
  // table, links to the index and dashboard. The site gets site-home.md instead.
  "home.md",
])

// Assessment registers ARE published — students get real value from the per-item
// dates, formats and AO focus. Their internal parts (the "Announced"/"Gap" columns,
// the notice-correction and timetable-redraw callouts, and the trailing rules/
// open-items sections) are stripped by cleanRegister() below. Nothing is withheld
// wholesale by directory anymore.
//
// The exception is the deck workshop. Each course's `decks/` folder holds the
// built .pptx files (published — see decks.mjs) beside two folders of source
// material that must not be: `_build/` (build scripts, collegiate.js, verify.py,
// BUILD-NOTES.md) and `_assets/` (full-resolution sources, CREDITS.md). Their
// .md files would otherwise be published verbatim as pages, since walk() takes
// every .md in the vault. CREDITS.md is not lost — decks.mjs republishes it as a
// single reader-facing credits page at /decks/credits.
const DROP_DIRS = [`/${DECKS_DIR}/_build/`, `/${DECKS_DIR}/_assets/`]

// H2 sections removed from every page that has them.
const STRIP_SECTIONS = [
  "Teacher notes",
  "Contingencies",
  "Contingencies & open items",
  "Open items",
  "Open items, explained",
  // Assessment-register rule sections: internal scheduling logic, and the general
  // grading rules they restate are already on the published framework page.
  "Applied rules",
  "Notice and marking rules", // "…, as applied"
  "The 13 applied handbook rules", // PAL; heading actually reads "(compact)"
  "Gaps",
  "Image and library needs",
  "Class workspace", // raw/ paths and ingest instructions
  "Holdings", // inventory of source files in raw/
  // Resource-library catalog sections: teacher inventory of raw/ teaching files,
  // with slide counts, an "I cannot watch video" note, and worksheet-as-assessment
  // warnings. The reading sections are kept and cleaned by cleanResourceLibrary().
  "Slide decks",
  "Videos",
  "Worksheets",
  // Course-overview sections that are planning notes about the vault itself:
  // which sources disagree, what is still undecided, what is missing.
  "⚠ Old-spec traps",
  "⚠ The syllabus straddle",
  "Open decisions",
  "Known inconsistencies",
  "Missing from",
  "Flags",
  "Two generations of the course",
  "Teaching materials",
  "Heavy dependence on the shared library",
  "Shared-library touchpoints",
  "Information needed",
  // Unit-page sections added 2026-07-20: teacher mappings of raw/ files to sessions,
  // and prior-year plan mining notes. Both reference raw/ paths and usage guidance.
  "Resources",
  "Prior plan",
  "Course-wide references", // resource-library catalog section (AO guide, elements chart)
]

// Matched as a prefix, so "## Gaps this material does *not* fill" is caught by "Gaps".
// Safe for this list: none of these names begins a student-facing heading.

const isDropped = (rel) => DROP_PAGES.has(rel) || DROP_DIRS.some((d) => rel.includes(d))

async function walk(dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...(await walk(full)))
    else if (entry.name.endsWith(".md")) out.push(full)
  }
  return out
}

// Remove an H2 section: the heading through to the next H2 or end of file.
function stripSections(body) {
  for (const name of STRIP_SECTIONS) {
    const esc = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    // Terminate at the next H2 or end of file. JS has no \z, so the alternative
    // is a negative lookahead for any remaining character.
    body = body.replace(new RegExp(`^## ${esc}.*$[\\s\\S]*?(?=^## |(?![\\s\\S]))`, "gm"), "")
  }
  return body
}

// Split a markdown table row into cells, respecting `\|` escapes — the registers
// carry `[[path\|alias]]` wikilinks whose pipe must not be read as a column break.
function splitRow(line) {
  const cells = line.split(/(?<!\\)\|/)
  if (cells.length && cells[0].trim() === "") cells.shift()
  if (cells.length && cells[cells.length - 1].trim() === "") cells.pop()
  return cells
}

// Remove named columns from every GitHub-style table in the text. Used to drop the
// internal "Announced" and "Gap" columns while keeping the student-facing ones.
function dropTableColumns(body, dropHeaders) {
  const lines = body.split("\n")
  const out = []
  for (let i = 0; i < lines.length; i++) {
    const sep = lines[i + 1]
    const isTableHead =
      lines[i].includes("|") && sep && /-/.test(sep) && /^\s*\|?[\s:|-]+\|[\s:|-]*$/.test(sep)
    if (!isTableHead) {
      out.push(lines[i])
      continue
    }
    const drop = new Set(
      splitRow(lines[i])
        .map((h, idx) => (dropHeaders.includes(h.trim()) ? idx : -1))
        .filter((idx) => idx >= 0),
    )
    if (drop.size === 0) {
      out.push(lines[i])
      continue
    }
    let j = i
    while (j < lines.length && lines[j].includes("|") && lines[j].trim() !== "") {
      const kept = splitRow(lines[j]).filter((_, idx) => !drop.has(idx))
      out.push("| " + kept.map((c) => c.trim()).join(" | ") + " |")
      j++
    }
    i = j - 1
  }
  return out.join("\n")
}

// Exam integrity, not privacy (2026-08-04): two lesson bodies name the sealed
// Cambridge papers used for the L15 rehearsal and the End-of-Term sitting. On
// the student site a named paper is a watchable extract and a readable mark
// scheme, and the sitting depends on the extract being unseen. The vault keeps
// the identities; the site gets the fact without them. Applied in phase 1, so
// the model never sees the names. reframe.mjs carries matching LEAK_MARKERS in
// case a future vault edit reintroduces them in a phrasing these regexes miss.
const SEALED_PAPERS = {
  "classes/media-studies/lesson-plans/9607-s1-lesson-15-exam-rehearsal.md": [
    [/the \*Your Honor\* rehearsal paper/g, "a sealed past paper"],
  ],
  "classes/media-studies/lesson-plans/9607-s1-lesson-16-end-of-term-exam-and-return.md": [
    [/The paper: June 20\d\d\/\d\d \(\*Servant\*\)/g, "The paper stays sealed until the sitting"],
  ],
}

// The whole-paragraph and sentence-level internal bits that survive the section and
// column strips — announcement scheduling, timetable contingencies, planning stamps.
// Matched by distinctive substrings so the surrounding student-facing prose stays.
const INTERNAL_PARAGRAPHS = [
  "exposed to Foreign Culture Day", // 9479 CS Friday-slip note
  "each derived against", // Art App Majors intro (announcement scheduling)
  "announcements land 14 days ahead", // PAL attainment note
  "CS notice per handbook", // PAL CS note
  "the two remaining courses with the same gap", // 9479 Final cross-course contrast
  // PAL sketchbook (2026-07-20): A5 (2027-01-06) and the two spot-checks SB1/SB2 are
  // all dated now and publish via the register tables + clean notes. Still teacher-only:
  "Format spec exists", // EoT pointer into prior-plans (teacher material)
]

// Register-only cleanup, on top of the shared section strip.
function cleanRegister(body) {
  // Every blockquote in these registers is internal: the notice-rule correction,
  // the "timetable has no Thursday" redraw, and the `> **Codes:**` mapping note.
  body = body.replace(/(?:^>.*(?:\n|$))+/gm, "")

  body = dropTableColumns(body, ["Announced", "Gap"])

  body = body
    .split(/\n\n+/)
    .filter((para) => !INTERNAL_PARAGRAPHS.some((s) => para.includes(s)))
    .join("\n\n")

  // Register-only planning tails. (The "Confirmed by the human" stamp is handled
  // globally by stripStamp, since it appears on many non-register pages too.)
  // These run from their marker to the end of the paragraph and stop at the break,
  // so the following heading survives.
  body = body
    .replace(/[ \t]*\*\*Resolved [^*]*?\.\*\*[ \t]*/g, "")
    .replace(/[ \t]*Open question:[\s\S]*?(?=\n\n|$)/g, "")
    .replace(/[ \t]+\n/g, "\n")

  return body
}

// The vault stamps human-confirmed facts as "Confirmed by the human <date>" (and a
// lowercase "(confirmed <date>)" variant) — an authoring convention, never for
// students. Drop the stamp, keep the fact. Applied to every page. Same treatment
// for ingest stamps ("(ingested 2026-07-20)", "Ingested 2026-07-19.") — they date
// when a source entered the vault, which means nothing to a reader.
function stripStamp(body) {
  return (
    body
      // Prefix form "Confirmed by the human <date>: Fact" / "…<date>, Fact" → "Fact".
      .replace(
        /Confirmed by the human 20\d\d-\d\d-\d\d[:,]\s*(\*{0,2})([a-z])/g,
        (_, emph, ch) => emph + ch.toUpperCase(),
      )
      // Standalone / trailing stamp, with any leading comma, semicolon or space.
      .replace(/[,;]?\s*Confirmed by the human 20\d\d-\d\d-\d\d/g, "")
      // Parenthetical "(confirmed with the human <date>)" variant.
      .replace(/\s*\((?:re-?)?confirmed with the human[^)]*\)/gi, "")
      // Lowercase parenthetical "(confirmed <date>[, …])", incl. "(re-confirmed 07-20)".
      .replace(/\s*\((?:re-?)?confirmed (?:20\d\d-)?\d\d-\d\d[^)]*\)/gi, "")
      // Ingest stamps: "(ingested 2026-07-20)" — inline and in headings — and the
      // standalone sentence "Ingested 2026-07-19."
      .replace(/\s*\((?:re-)?ingested (?:20\d\d-)?\d\d-\d\d[^)]*\)/gi, "")
      .replace(/\s*Ingested 20\d\d-\d\d-\d\d\./g, "")
      // Empty bold left when the stamp was the whole bold span: "**** — a studio…" →
      // "A studio…"; bare "****" → "". Four contiguous asterisks only: a spaced
      // "** **" is two legitimate adjacent bold spans ("**Answer:** **Technical**"
      // in the practice quizzes), and stamp removal always consumes its leading
      // whitespace, so real residue never carries an inner space.
      .replace(/\*\*\*\*\s*—\s*([a-z])/g, (_, ch) => ch.toUpperCase())
      .replace(/\*\*\*\*/g, "")
      .replace(/[ \t]{2,}/g, " ")
      .replace(/[ \t]+([.,;])/g, "$1")
  )
}

// Students see assessments at their real dates (the calendar and the register tables).
// The vault also models when each is *announced* — teacher scheduling that means nothing
// to a student. Strip the announcement notes, keeping the assignment itself. Not applied
// to the framework page, which legitimately explains the one-week notice policy.
function stripAnnouncements(body) {
  return (
    body
      // Parenthetical note that mixes announcement with a return date:
      // "(announced 11-13; returned Tue 12-01)" → "(returned Tue 12-01)".
      .replace(/\(announced [^;)]*;\s*/gi, "(")
      // Announcement-only parenthetical: "(announced 09-30)" / "(announced Tue 12-01)" → "".
      .replace(/\s*\(announced[^)]*\)/gi, "")
      // Clause after a sit date: "sits <date>, announced <date> — see …" → drop the clause.
      // The lookahead leaves the boundary punctuation and any space before it intact, so
      // "sits <date>, announced <date> — see" becomes "sits <date> — see", not "…date— see".
      .replace(/\s*[—,]\s*announced\b[^.;,—|)]*?(?=\s*[.;,—|)]|$)/gi, "")
      // Prose clause "…; announced <date> (reason)…" → drop to the next . ; or cell edge.
      .replace(/;\s*announced\b[^.;|]*?(?=\s*[.;|]|$)/gi, "")
      // Whole bold sentence about announcement: "**A4 is announced on the A3 sitting day**".
      .replace(/\*\*A\d is announced[^*]*\*\*/gi, "")
      // Session-table / inline markers, with an optional leading "·" or ";" separator:
      // "A2 announced", "A1 + CS1 announced", "**A3 announced**", "**CS4** · A4 announced".
      .replace(/(?:\s*[·;]\s*)?\*{0,2}A\d(?:\s*\+\s*CS\d)?\s+announced\*{0,2}/g, "")
      // Register cell note "— announced with A1 on 09-16" and "A4's announcement on 12-16".
      .replace(/\s*—?\s*announced with [^|.\n]*/gi, "")
      .replace(/\s*A\d's announcement on \d\d-\d\d/gi, "")
      // "announced here at U1·L10" / "**announced here**" and bare "announced here".
      .replace(/\*{0,2}announced here\*{0,2}(?:\s+at\s+[^.;|]*)?/gi, "")
      // Register-pointer phrasing on semester/unit pages: keep the pointer, drop the
      // "announcement dates and rules" / "the announcement rule (…)" descriptor.
      .replace(/\s*with (?:the full )?announcement dates and rules/gi, "")
      .replace(/\s*with the announcement rule \([^)]*\)/gi, "")
      // Tidy: empty parens, cell-initial dangling separators, doubled spaces.
      .replace(/\(\s*\)/g, "")
      .replace(/(\|\s*)[;·]\s+/g, "$1")
      .replace(/[ \t]{2,}/g, " ")
      .replace(/[ \t]+([.,;])/g, "$1")
      .replace(/[ \t]+\|/g, " |")
      .replace(/[ \t]+\n/g, "\n")
  )
}

// The resource-library page is a teacher catalog of raw/ files. With its inventory
// sections stripped (Slide decks / Videos / Worksheets / Gaps), what remains is the
// two reading tables — this reframes them as a student reading list: the "teacher
// reference" shelf becomes "Further reading", and the catalog/ingest framing goes.
function cleanResourceLibrary(body) {
  return (
    body
      .replace(/^## Readings — teacher reference\s*$/m, "## Further reading")
      // Framing lines written for the teacher, not the reader.
      .replace(/^Not student-facing\. [^\n]*\n/m, "")
      .replace(/^Confirmed with the human 20\d\d-\d\d-\d\d as student-facing\.\s*\n/m, "")
      .replace(/^Catalog of `raw\/[^\n]*\n/m, "")
      .replace(/^\*\*Catalogued, not transcribed\.\*\* [^\n]*\n/m, "")
      .replace(/^The important thing this drop changes:[^\n]*\n/m, "")
      // Closing line of vault analysis ("assembled for the current arc, not the prior unit").
      .replace(/^Six of the seven map onto lessons[^\n]*\n/m, "")
      .replace(/\n{3,}/g, "\n\n")
  )
}

// The calendar page carries Obsidian-only framing: a pointer to the Full Calendar
// plugin (which doesn't exist on the web) and a vault-maintenance "derived view"
// note. Strip both so the agenda reads as the calendar, not a mirror of one.
function cleanCalendar(body) {
  return (
    body
      .replace(/\s*For the visual month\/week view[\s\S]*?greppable list\./, "")
      .replace(/^This is a \*derived view\*[\s\S]*?needs fixing\.\s*$/m, "")
      // The "⚠️ Confirm before term" section is a teacher's pre-term checklist
      // (TBC items, resolution history). Drop the section but keep its closing
      // italic note — that paragraph tells students where CS/HW schedules live.
      .replace(/^## ⚠️? ?Confirm before term[\s\S]*?(?=^\*This calendar lists|(?![\s\S]))/m, "")
      .replace(/\n{3,}/g, "\n\n")
  )
}

// Withheld pages whose student-relevant content lives on another published page:
// links to them are retargeted there instead of degrading to plain text.
const LINK_REDIRECTS = {
  // The hub calendar is a strict superset of the school calendar's dates.
  "shared/school-academic-calendar": "calendar",
}

// Links to withheld pages are retargeted (if a redirect exists) or become plain
// text, so the site has no dead ends. Handles [[path]], [[path|alias]] and the
// [[path\|alias]] form used inside tables.
function derefDropped(text, publishedTargets) {
  return text.replace(/\[\[([^\]|]+?)(?:(\\?\|)([^\]]*?))?\]\]/g, (match, target, pipe, alias) => {
    const clean = target.split("#")[0].trim()
    if (publishedTargets.has(clean)) return match
    // Humanize the slug for bare links, so prose reads "the school academic
    // calendar", not "the school-academic-calendar".
    const label = alias ?? clean.split("/").pop().replace(/-/g, " ")
    const redirect = LINK_REDIRECTS[clean]
    if (redirect) return `[[${redirect}${pipe ?? "|"}${label}]]`
    return label
  })
}

// Drop `sources:` (raw/ paths are internal), `tags:` (vault taxonomy — the site
// has no tag pages), and prune `related:` of withheld pages.
function cleanFrontmatter(fm, publishedTargets) {
  const lines = fm.split("\n")
  const kept = []
  let inSources = false
  for (const line of lines) {
    if (/^tags:/.test(line)) continue
    // Marking-queue keys on the assessment pages (assessment/due/returned) are
    // teacher workflow, not student content. Added vault-side 2026-08-02.
    if (/^(assessment|due|returned):/.test(line)) continue
    if (/^sources:/.test(line)) {
      inSources = true
      continue
    }
    if (inSources) {
      if (/^\s+-\s/.test(line)) continue
      inSources = false
    }
    // Prune related: entries whose target is withheld.
    const relatedEntry = line.match(/^\s+-\s+"\[\[([^\]|]+?)(?:\|[^\]]*)?\]\]"\s*$/)
    if (relatedEntry && !publishedTargets.has(relatedEntry[1].split("#")[0].trim())) continue
    // content/ is regenerated on every sync, so filesystem mtimes are meaningless.
    // The vault's own last_updated is the honest date; Quartz reads `modified`.
    kept.push(line.replace(/^last_updated:/, "modified:"))
  }
  return kept.join("\n")
}

const files = await walk(VAULT)
const published = files.map((f) => relative(VAULT, f)).filter((rel) => !isDropped(rel))

// Wikilinks in this vault use full vault-relative paths without the .md suffix.
const publishedTargets = new Set(published.map((rel) => rel.replace(/\.md$/, "")))

// ── Phase 1: deterministic filter ───────────────────────────────────────────
// This is the privacy gate. Everything below runs before any model sees a page:
// withheld pages and stripped sections never leave this machine.

// rel → frontmatter title, for the course maps and nav labels.
const pageTitles = new Map()
// lesson rel → base filename of the unit it belongs to (from its `related`
// frontmatter links), so the course map can nest lessons under their units.
const lessonUnits = new Map()
let strippedCount = 0
const pages = []
for (const rel of published) {
  let raw = await readFile(join(VAULT, rel), "utf8")

  const fmMatch = raw.match(/^---\n([\s\S]*?)\n---\n/)
  let frontmatter = ""
  let body = raw
  if (fmMatch) {
    frontmatter = cleanFrontmatter(fmMatch[1], publishedTargets)
    body = raw.slice(fmMatch[0].length)
    const t = fmMatch[1].match(/^title:\s*"?(.+?)"?\s*$/m)
    if (t) pageTitles.set(rel, t[1])
    if (rel.includes("lesson-plans/")) {
      const u = fmMatch[1].match(/unit-plans\/([^\]|/\n]+)/)
      if (u) lessonUnits.set(rel, u[1])
    }
  }

  const before = body.length
  body = stripSections(body)
  if (rel.includes("/assessments/")) body = cleanRegister(body)
  if (rel.endsWith("resource-library.md")) body = cleanResourceLibrary(body)
  if (rel === "calendar.md") body = cleanCalendar(body)
  body = stripStamp(body)
  // The framework page explains the one-week notice policy — student-useful, keep it.
  if (rel !== "shared/bnds-assessment-framework.md") body = stripAnnouncements(body)
  for (const [re, sub] of SEALED_PAPERS[rel] ?? []) body = body.replace(re, sub)
  if (body.length !== before) strippedCount++

  // The Bases plugin embed can't render outside Obsidian.
  body = body.replace(/^!\[\[dashboard\.base\]\]\s*$/gm, "")

  body = derefDropped(body, publishedTargets)
  body = body.replace(/\n{3,}/g, "\n\n").trimEnd() + "\n"

  // After every deterministic clean, so the practice text got the same
  // treatment (links dereferenced, stamps stripped) as the rest of the page.
  let practice = ""
  if (rel.includes("lesson-plans/")) ({ body, practice } = splitPractice(body))

  pages.push({ rel, frontmatter, body, practice })
}

// ── Assessment-date consistency (advisory) ──────────────────────────────────
// Dates are prose in the vault, so a redraw can move a sitting in the register
// and miss a lesson body (July 2026 did exactly that). date-check.mjs compares
// every assessment-code date mention — lesson prose, briefs, unit plans, the
// calendar-events files — against the registers, which are the declared truth.
// Findings print as plain lines, never ⚠: they surface in every auto-sync log
// without blocking a publish. Also runs standalone: node date-check.mjs.
for (const finding of await checkDates(VAULT)) console.log(finding)

// ── Phase 2: student-voice reframe ──────────────────────────────────────────
// The filter above can only *delete* teacher material; the surviving prose is
// still written in the vault's planning voice. This stage rewrites each body
// for students via the Claude API (see reframe.mjs), cached by content hash so
// only changed pages cost a model call. It runs before content/ is cleared, so
// a failure aborts with the previous output intact.
const SKIP_REFRAME = new Set([
  // A dates-only agenda, already cleaned by cleanCalendar(); the month-view
  // injection below anchors on its "## … Agenda" heading, which must survive.
  "calendar.md",
])
const reframeStats = await reframeAll(
  pages.filter((p) => !SKIP_REFRAME.has(p.rel)),
  {
    cachePath: join(import.meta.dirname, "reframe-cache.json"),
    disabled: process.env.REFRAME === "off",
  },
)

// ── Student-facing titles ───────────────────────────────────────────────────
// Vault titles carry the teacher's taxonomy ("9607 S1 Lesson 02: …") — syllabus
// code and semester on every page. On the site the course is always visible
// (nav, breadcrumbs, the context strip), so titles keep only what a student
// needs: "Lesson 02: …". Course-level pages keep the course name because their
// names collide across courses in search ("Semester 1 Plan" × 5). Applied in
// phase 3, after the reframe, so the cache (keyed on the phase-1 body) is
// untouched. A Level spans four semesters with repeating unit names, so it
// keeps the S# marker.
const MULTI_SEMESTER = new Set(["classes/a-level-art-design"])

function studentTitle(rel, title) {
  const course = Object.values(COURSES).find((c) => rel.startsWith(c.dir + "/"))
  if (!course || !title) return title
  const multi = MULTI_SEMESTER.has(course.dir)
  let m = title.match(/^.*?\bS(\d)\s+Lesson (\d+):\s*(.+)$/i)
  if (m) return multi ? `S${m[1]} Lesson ${m[2]}: ${m[3]}` : `Lesson ${m[2]}: ${m[3]}`
  m = title.match(/^.*?\bS(\d)\s+U(?:nit)?\s*(\d+):\s*(.+)$/i)
  if (m) return multi ? `S${m[1]} Unit ${m[2]}: ${m[3]}` : `Unit ${m[2]}: ${m[3]}`
  m = title.match(/^.*?\bS(\d) Assessments$/i)
  if (m) return `${course.name} · S${m[1]} Assessments`
  m = title.match(/^(?:9479|9607|PAL|Art Appreciation|Pre A Level(?: Art & Design)?)\s+(.+)$/)
  if (m) return `${course.name} · ${m[1]}`
  return title
}

// Assessment codes link to their pages (2026-08-06): the first mention of
// each code on a page becomes a wikilink — attainments and the EoT to their
// brief page, CS/HW/SB/LB items to the course's Course Skills page, and on
// 9479's future semesters everything to that semester's register, since
// their briefs are not written yet. Presentation-layer, like studentTitle:
// the vault keeps plain codes. Tables (statStrip must still promote their
// rows), headings, blockquotes, raw HTML and existing links are left alone,
// and date-check's paper-size guard keeps "three A5 drawings" unlinked.
const A_DIR = {
  "classes/media-studies": {
    s1: {
      briefs: {
        A1: "9607-s1-a1-timed-media-language-analysis",
        A2: "9607-s1-a2-blog-mid-point",
        A3: "9607-s1-a3-c1-portfolio",
        A4: "9607-s1-a4-section-a-authentic-format",
        EoT: "9607-s1-eot-component-2-paper",
      },
      cs: "9607-s1-course-skills-and-homework",
    },
  },
  "classes/art-appreciation": {
    s1: {
      briefs: {
        A1: "art-appreciation-s1-a1-unit-1-board",
        A2: "art-appreciation-s1-a2-titian-manet-comparison",
        A3: "art-appreciation-s1-a3-food-and-ethics-essay",
        A4: "art-appreciation-s1-a4-unit-4-synthesis",
        EoT: "art-appreciation-s1-eot-retrospective",
      },
      cs: "art-appreciation-s1-course-skills",
    },
  },
  "classes/pre-a-level-art-design": {
    s1: {
      briefs: {
        A1: "pal-s1-a1-observational-drawing",
        A2: "pal-s1-a2-photographic-series",
        A3: "pal-s1-a3-final-collage",
        A4: "pal-s1-a4-final-poster",
        A5: "pal-s1-a5-sketchbook",
        EoT: "pal-s1-eot-semester-portfolio",
      },
      cs: "pal-s1-course-skills-and-homework",
    },
  },
  "classes/a-level-art-design": {
    s1: {
      briefs: {
        A1: "9479-s1-a1-recording-milestone",
        A2: "9479-s1-a2-exploration-and-artist-study",
        A3: "9479-s1-a3-development-milestone",
        A4: "9479-s1-a4-final-portfolio",
        EoT: "9479-s1-the-final",
      },
      cs: "9479-s1-course-skills",
    },
    s2: { register: "9479-s2-assessments" },
    s3: { register: "9479-s3-assessments" },
    s4: { register: "9479-s4-assessments" },
  },
}

function linkAssessmentCodes(body, rel, publishedTargets) {
  const course = Object.keys(A_DIR).find((dir) => rel.startsWith(dir + "/"))
  if (!course || rel.includes("/assessments/")) return body
  const sems = A_DIR[course]
  const sem = Object.keys(sems).length > 1 ? rel.match(/-(s\d)-/)?.[1] : Object.keys(sems)[0]
  const conf = sem && sems[sem]
  if (!conf) return body // no semester marker on a multi-semester course
  // A future-semester outline on a single-register course would mislink its
  // codes to this semester's pages.
  if (!sems.s2 && /semester-[2-9]/.test(rel)) return body

  const targetOf = (code) => {
    const page = conf.register ?? (/^(A\d|EoT)$/.test(code) ? conf.briefs[code] : conf.cs)
    if (!page) return null
    const target = `${course}/assessments/${page}`
    return publishedTargets.has(target) ? target : null
  }

  const linked = new Set()
  return body
    .split("\n")
    .map((line) => {
      if (line.includes("|") || line.includes("<") || /^\s*[#>]/.test(line)) return line
      return line.replace(/\b(A[1-5]|CS\d{1,2}|HW\d|SB\d|LB\d|EoT)\b/g, (code, _c, at) => {
        if (linked.has(code)) return code
        // Inside an existing wikilink, or a paper size, stays as written.
        if (line.lastIndexOf("[[", at) > line.lastIndexOf("]]", at)) return code
        const after = line.slice(at + code.length)
        if (PAPER.test(after) || PAPER_BEFORE.test(line.slice(0, at))) return code
        // "the A2 season/year" is A-Level terminology for the second year,
        // not the assessment.
        if (/^[- ]?(season|year|timeline|entry)\b/.test(after)) return code
        const target = targetOf(code)
        if (!target) return code
        linked.add(code)
        return `[[${target}|${code}]]`
      })
    })
    .join("\n")
}

// Bare full-path wikilinks render as their slug ("bnds-assessment-framework");
// alias them with the target's title so prose reads like prose. Table rows are
// skipped — a raw "|" inside a cell would break the row, and links there
// already use the [[path\|alias]] form.
function aliasBareLinks(body, titles) {
  return body
    .split("\n")
    .map((line) => {
      if (line.includes("|")) return line
      return line.replace(/\[\[([^\]|#\\]+)\]\]/g, (match, target) => {
        const title = titles.get(target.trim())
        return title ? `[[${target.trim()}|${title}]]` : match
      })
    })
    .join("\n")
}

// New titles for every published page, and the alias lookup keyed by wikilink
// target. pageTitles is updated in place so the course-map injection below and
// the nav labels derived from frontmatter stay consistent.
const studentTitles = new Map()
for (const rel of published) {
  const t = studentTitle(rel, pageTitles.get(rel))
  if (!t) continue
  pageTitles.set(rel, t)
  studentTitles.set(rel.replace(/\.md$/, ""), t)
}

// ── Phase 3: write content/ ─────────────────────────────────────────────────
// Everything is rewritten from scratch each run, except decks/: those are large
// binaries, and syncDecks() reconciles them against the vault by content hash
// rather than deleting and re-copying 40-odd MB into a cloud-synced folder every
// morning. It removes anything in there the vault no longer has, so the guarantee
// below — content/ holds only what this run put there — still holds.
for (const entry of await readdir(OUT).catch(() => [])) {
  if (entry === DECKS_DIR) continue
  await rm(join(OUT, entry), { recursive: true, force: true })
}
await mkdir(OUT, { recursive: true })

// Lesson decks: copy the .pptx files through and map each to its lesson page.
const decks = await syncDecks({
  vault: VAULT,
  out: OUT,
  courses: COURSES,
  lessonRels: published.filter((rel) => rel.includes("/lesson-plans/")),
})

// Every path this run writes, so anything else in content/ can be pruned at the end.
const written = new Set()
for (const { rel, frontmatter: fm, body: cleaned, practice } of pages) {
  let body = cleaned
  let frontmatter = fm

  // Student-facing title: rewrite the frontmatter `title:` and the H1 to match.
  // The reframe keeps H1s verbatim, so the original title is still on that line.
  const newTitle = pageTitles.get(rel)
  const oldTitle = fm?.match(/^title:\s*"?(.+?)"?\s*$/m)?.[1]
  if (newTitle && oldTitle && newTitle !== oldTitle) {
    frontmatter = frontmatter.replace(/^title:.*$/m, `title: "${newTitle}"`)
    body = body.replace(`# ${oldTitle}`, `# ${newTitle}`)
  }

  body = aliasBareLinks(body, studentTitles)
  // Before the practice append, so answer reveals keep their links-free rule
  // and the first linked mention lands in the main body.
  body = linkAssessmentCodes(body, rel, publishedTargets)

  const depth = rel.split("/").length - 1
  // Figures first: their anchors must match page content, not the hero's caption.
  if (FIGURES[rel]) body = insertFigures(body, FIGURES[rel], depth, rel)
  if (HANDOUTS[rel]) body = insertHandouts(body, HANDOUTS[rel], depth, rel)
  if (CHECKLISTS[rel]) body = insertChecklist(body, CHECKLISTS[rel], rel)
  if (CITATIONS[rel]) body = insertCitations(body, CITATIONS[rel], rel)
  const deck = decks.byLesson.get(rel)
  if (deck) body = insertDeckLine(body, deckLine(deck, depth))
  // After the figure inserts, so an unmatched figure's end-of-body fallback
  // lands above Practice, which stays the page's last section.
  if (practice)
    body = body.trimEnd() + "\n\n" + practiceDetails(aliasBareLinks(practice, studentTitles))
  // Last of the body transforms: insertHandouts anchors on "| Unit |" and
  // insertDeckLine on the first "## ", and both must still see the page as the vault
  // wrote it.
  body = statStrip(body)
  if (HEROES[rel]) body = heroFigure(HEROES[rel], depth) + body

  const dest = join(OUT, rel)
  await mkdir(dirname(dest), { recursive: true })
  await writeFile(dest, frontmatter ? `---\n${frontmatter}\n---\n${body}` : body)
  written.add(rel)
}

// syncDecks() has already written the credits page; claim it so the stray sweep
// at the end (which sees every .md in content/) doesn't take it back out.
if (decks.credits) written.add(decks.credits)

// The site's own landing page, kept in this repo rather than the vault. Its
// `hero:` frontmatter key names a plate the same way HEROES does for vault pages.
let home = await readFile(join(import.meta.dirname, "site-home.md"), "utf8")
const homeHero = home.match(/^hero:\s*(\S+)\s*$/m)
if (homeHero) {
  home = home.replace(/^hero:.*\n/m, "")
  home = home.replace(/^(---\n[\s\S]*?\n---\n)/, `$1\n${heroFigure(homeHero[1], 0)}`)
}
// The landing masthead, counted from what this run published rather than typed into
// site-home.md, where "16 lessons" would quietly go stale the week a seventeenth landed.
// The placeholder is an HTML comment, so an un-run sync degrades to nothing visible.
home = home.replace(
  /^<!--stat-strip-->$/m,
  // Three cells, not four: the landing article is 652px, where a fourth wraps alone onto
  // its own row and stretches the full width. The first teaching day was the cell that
  // went, and "Key dates" states it in the next screen anyway.
  stripHtml([
    { label: "Courses", value: String(Object.keys(COURSES).length) },
    { label: "Lessons", value: String([...written].filter((r) => /\blesson-\d+/.test(r)).length) },
    { label: "Semester", value: "Sep 2026 → Jan 2027" },
  ]).trimEnd(),
)
await writeFile(join(OUT, "index.md"), home)
written.add("index.md")

// Curated folder pages. Quartz auto-generates a listing page for every
// directory ("Folder: classes/media-studies/lesson-plans" with raw slugs); these
// index files give each one a real title and a line of context instead. The
// child listing still renders below the body.
const folderIndexes = {
  classes: {
    title: "All courses",
    body:
      // Cohort beside each course name: this page is a chooser, and "which one is mine"
      // is the only question a student brings to it.
      "Every course on this site. Start from a course overview:\n\n" +
      Object.values(COURSES)
        .map((c) => `- [[${c.overview}|${c.name}]] — ${c.cohort}${c.code ? ` · ${c.code}` : ""}`)
        .join("\n"),
  },
  concepts: {
    title: "Concepts",
    body: "Concept pages used across Media Studies: the place to start when revising.",
  },
  entities: {
    title: "Theorists",
    body: "The theorists studied in Media Studies, one page each.",
  },
  shared: {
    title: "School reference",
    body: "School-wide reference pages that apply to every course.",
  },
  [DECKS_DIR]: {
    title: "Lesson slides",
    body:
      "The slides shown in class. Most are lesson decks, linked from the lesson " +
      "page they belong to; the studio courses teach in doubles and deck at course " +
      "level instead, so theirs, the introductions and the assignment briefs, are " +
      "linked from the course overview. This folder also carries the " +
      "[[decks/credits|image credits]] for every work they reproduce.",
  },
}
for (const c of Object.values(COURSES)) {
  folderIndexes[c.dir] = {
    title: `${c.name} · All pages`,
    body: `Everything published for ${c.name}. Start at the [[${c.overview}|course overview]].`,
  }
  folderIndexes[`${c.dir}/lesson-plans`] = {
    title: `${c.name} · Lessons`,
    body: `Every ${c.name} lesson, in teaching order.`,
  }
  folderIndexes[`${c.dir}/unit-plans`] = {
    title: `${c.name} · Units & plans`,
    body: `${c.name} unit pages and semester plans.`,
  }
  folderIndexes[`${c.dir}/assessments`] = {
    title: `${c.name} · Assessments`,
    body: `The ${c.name} assessment register: every graded item with its date and format.`,
  }
}
for (const [dir, page] of Object.entries(folderIndexes)) {
  // Only folders this run actually populated.
  if (![...written].some((rel) => rel.startsWith(dir + "/"))) continue
  const rel = `${dir}/index.md`
  await writeFile(join(OUT, rel), `---\ntitle: "${page.title}"\n---\n${page.body}\n`)
  written.add(rel)
}

// Month-grid calendars, generated from the agenda table (the single source of truth).
// One page per course, plus the combined grid injected into the hub calendar page.
const events = parseAgenda(await readFile(join(VAULT, "calendar.md"), "utf8"))

for (const key of Object.keys(COURSES)) {
  // Detail layer: every graded item from the course's registers, lesson runs from
  // the lesson plans, and unit spans — parsed straight from the vault.
  const detail = await courseDetailEvents(VAULT, COURSES[key].dir)
  const { rel, content } = coursePage(key, events, detail)
  const dest = join(OUT, rel)
  await mkdir(dirname(dest), { recursive: true })
  await writeFile(dest, content)
  written.add(rel)
}

// Inject the combined month view into the hub calendar page, above the text agenda.
const calRel = "calendar.md"
let cal = await readFile(join(OUT, calRel), "utf8")
const courseLinks =
  "**Per-course calendars:** " +
  Object.values(COURSES)
    .map((c) => `[[${c.dir}/course-calendar|${c.name}]]`)
    .join(" · ")
cal = cal.replace(
  /\n(## [^\n]*Agenda)/,
  `\n## Month view\n\n${calendarBlock(events, null)}\n\n${courseLinks}\n\n$1`,
)
await writeFile(join(OUT, calRel), cal)

// The Image-library gallery: one page of every downsampled (public-domain) plate
// — the hand-curated heroes (credits.json) plus the bulk batch from
// library-images.mjs (library-credits.json, absent until it has been run).
let libCredits = {}
try {
  libCredits = JSON.parse(await readFile(join(import.meta.dirname, "library-credits.json"), "utf8"))
} catch {
  /* library-images.mjs not run yet — gallery shows the heroes only */
}
// Era / medium / movement per plate, for the filter rows. Regenerate with
// `node taxonomy.mjs` after a new batch of plates; until every plate is in it the
// gallery falls back to the unfiltered wall rather than hiding the new ones.
let taxonomy = {}
try {
  taxonomy = JSON.parse(await readFile(join(import.meta.dirname, "library-taxonomy.json"), "utf8"))
} catch {
  /* taxonomy.mjs not run yet — gallery shows one ungrouped wall */
}
await writeFile(join(OUT, "library.md"), libraryMarkdown(credits, libCredits, taxonomy))
written.add("library.md")

// Inject a structured course map into each overview, replacing the old inline
// "Start here" sentence links. Built from what was actually published, so it
// cannot list a page that doesn't exist. Course-level decks — the orientation
// and assignment-brief slides belonging to a course rather than any one lesson —
// go in directly below it.
for (const c of Object.values(COURSES)) {
  const ovRel = c.overview + ".md"
  if (!written.has(ovRel)) continue
  const prefix = c.dir + "/"
  const items = [...written]
    .filter((rel) => rel.startsWith(prefix) && rel !== ovRel)
    .map((rel) => ({
      rel: rel.slice(prefix.length),
      title: pageTitles.get(rel) ?? rel.split("/").pop().replace(/\.md$/, ""),
      unit: lessonUnits.get(rel),
    }))
  const map = courseMapHtml(items, c.dir)
  const courseDecks = decks.byCourse.get(c.dir)
  const slides = courseDecks ? courseDeckBlock(courseDecks, ovRel.split("/").length - 1) : ""
  if (!map && !slides) continue

  // The overview's own At-a-glance: who the course is for, and how much of it there is.
  // Counted from what was actually published this run — the same list the map is built
  // from — so the strip can never claim a lesson that isn't on the site. A count of 0 is
  // dropped rather than shown, because "0 lessons" reads as broken rather than as
  // not-yet-written (Oxbridge has no numbered lessons at all).
  const n = (re) => items.filter((it) => re.test(it.rel)).length
  const counts = [
    { label: "Units", value: n(/^unit-plans\/.*\bunit-\d+/) },
    { label: "Lessons", value: n(/^lesson-plans\/.*\blesson-\d+/) },
    // Registers and the folder index are navigation, not graded items.
    {
      label: "Assessments",
      value: items.filter(
        (it) =>
          it.rel.startsWith("assessments/") &&
          !/(^|\/)index\.md$/.test(it.rel) &&
          !/-assessments?\.md$/.test(it.rel),
      ).length,
    },
  ]
  const strip = stripHtml([
    { label: "Cohort", value: c.cohort, note: c.code },
    ...counts.filter((x) => x.value > 0).map((x) => ({ label: x.label, value: String(x.value) })),
  ])
  let ov = await readFile(join(OUT, ovRel), "utf8")
  // The old navigation: a "> **Start here:** …" blockquote of inline links,
  // and the "Semester plans / Assessment registers" blockquote — both now
  // covered by the map's semester cards.
  ov = ov.replace(/^> \*\*Start here:\*\*[^\n]*\n+/m, "")
  ov = ov.replace(/^> \*\*Semester plans:\*\*[^\n]*(?:\n> [^\n]*)*\n+/m, "")
  // Insert before the first H2 — after the intro prose, before the content.
  const block = strip + map + slides
  ov = /^## /m.test(ov) ? ov.replace(/^## /m, `${block}## `) : ov + "\n" + block
  await writeFile(join(OUT, ovRel), ov)
}

// content/ sits under ~/Documents, which is cloud-synced. When this script clears
// the directory, the sync client restores what it just deleted as conflict copies
// ("index 2.md"), and those land in content/ *after* the filter has run — so they
// reach the site unchecked. That is a filter bypass, not just clutter: a conflict
// copy of a withheld page would be published.
//
// Deleting anything this run did not itself write makes content/ exactly the
// filter's output, whatever else tries to appear in it.
const strays = (await walk(OUT)).map((f) => relative(OUT, f)).filter((rel) => !written.has(rel))

for (const rel of strays) await rm(join(OUT, rel))
if (strays.length) {
  console.log(`Removed ${strays.length} stray file(s) not produced by this sync:`)
  for (const rel of strays.slice(0, 5)) console.log(`  ${rel}`)
  if (strays.length > 5) console.log(`  … and ${strays.length - 5} more`)
}

console.log(
  `Published ${published.length} of ${files.length} pages ` +
    `(${files.length - published.length} withheld, ${strippedCount} had sections stripped) ` +
    `+ the site landing page.`,
)
console.log(
  `Reframed for students: ${reframeStats.cached} from cache, ` +
    `${reframeStats.rewritten} rewritten` +
    (reframeStats.kept ? `, ⚠ ${reframeStats.kept} published unreframed` : "") +
    `.`,
)
// Deck accounting is printed every run, whether or not anything changed, so a set
// that quietly shrinks is visible in the log and in the auto-sync commit message.
// Its warnings carry ⚠, which is auto-sync's signal to publish nothing and retry.
console.log(decks.summary)
for (const rel of decks.removed) console.log(`  removed deck ${rel}`)
for (const warning of decks.warnings) console.log(warning)
